import { evaluate, type Part } from '../circuit-builder/model'

export type Case = { id: string; title: string; story: string; parts: Part[]; options: string[]; answer: number; fixSlot: number; fixed: Part; explain: string }

const W: Part = { type: 'wire' }

export const CASES: Case[] = [
  { id: 'switch', title: 'The dark study lamp', story: 'Adam’s study lamp won’t light. The cell is new and the bulb is fine.', parts: [{ type: 'cell' }, { type: 'switch', closed: false }, { type: 'bulb' }, W, W, W], options: ['The switch is open', 'The bulb is fused', 'The cell is dead', 'The wire is too long'], answer: 0, fixSlot: 1, fixed: { type: 'switch', closed: true }, explain: 'An open switch leaves a gap in the circuit.' },
  { id: 'dead', title: 'The torch that died', story: 'A torch was left on all night. Now it won’t light at all.', parts: [{ type: 'cell', dead: true }, { type: 'switch', closed: true }, { type: 'bulb' }, W, W, W], options: ['The bulb is the wrong way round', 'The cell is used up (dead)', 'The switch is open', 'Torches only work in the day'], answer: 1, fixSlot: 0, fixed: { type: 'cell' }, explain: 'A used-up cell can no longer push current round the circuit.' },
  { id: 'led', title: 'The stubborn LED', story: 'A science-fair model has two new cells and an LED, but the LED stays dark.', parts: [{ type: 'cell' }, { type: 'cell' }, { type: 'led', reversed: true }, W, W, W], options: ['LEDs need AC current', 'The LED is connected the wrong way round', 'Two cells are too many', 'The wires are too short'], answer: 1, fixSlot: 2, fixed: { type: 'led' }, explain: 'An LED only lets current through one way: the longer leg must connect towards the + terminal.' },
  { id: 'ruler', title: 'The ruler shortcut', story: 'Riya ran out of wire and used a plastic ruler to bridge a gap.', parts: [{ type: 'cell' }, { type: 'bulb' }, W, { type: 'material', id: 'plastic' }, W, W], options: ['Plastic is an insulator', 'The ruler is too short', 'Plastic is magnetic', 'The bulb needs two cells'], answer: 0, fixSlot: 3, fixed: { type: 'material', id: 'foil' }, explain: 'Plastic doesn’t conduct. Replacing it with aluminium foil completes the circuit.' },
  { id: 'cancel', title: 'Two cells, no light', story: 'A toy car has two cells, but nothing works. One cell looks different…', parts: [{ type: 'cell' }, { type: 'cell', reversed: true }, { type: 'bulb' }, W, W, W], options: ['Both cells are dead', 'One cell is the wrong way round, so they cancel', 'The bulb is fused', 'The toy needs a switch'], answer: 1, fixSlot: 1, fixed: { type: 'cell' }, explain: 'Cells must point the same way (+ to −) so their pushes add up.' },
  { id: 'fused', title: 'The pop!', story: 'A bulb went ‘pop’ with a flash and now won’t light. Looking closely, you see a gap in the thin wire inside.', parts: [{ type: 'cell' }, { type: 'switch', closed: true }, { type: 'bulb', fused: true }, W, W, W], options: ['The filament is broken (the bulb is fused)', 'The cell is reversed', 'The switch is open', 'The bulb is too bright'], answer: 0, fixSlot: 2, fixed: { type: 'bulb' }, explain: 'A broken filament is a gap in the circuit inside the bulb.' },
  { id: 'onecell', title: 'The faint hope', story: 'An LED circuit uses just one 1.5 V cell. The LED is the right way round, but it doesn’t glow.', parts: [{ type: 'cell' }, { type: 'led' }, W, W, W, W], options: ['The LED needs more voltage: add another cell', 'LEDs never work with cells', 'The wire is broken', 'The LED is reversed'], answer: 0, fixSlot: 2, fixed: { type: 'cell' }, explain: 'Most LEDs need about 2 V; two 1.5 V cells give 3 V.' },
]

export const works = (parts: Part[]) => evaluate(parts).reason === 'works'
export const fixedParts = (c: Case) => c.parts.map((p, i) => (i === c.fixSlot ? c.fixed : p))
