export type Checkpoint = { km: number; heart: number; breaths: number; tempC: number; sweatL: number; question: string; options: string[]; answer: string; why: string }

/** Readings from a runner in the Bengaluru half marathon on a warm morning, and questions for the medic. */
export const CHECKPOINTS: Checkpoint[] = [
  { km: 0, heart: 72, breaths: 15, tempC: 37.0, sweatL: 0, question: 'At the start line, which system will need to work MUCH harder once the race starts?', options: ['Only the digestive system', 'The respiratory and circulatory systems', 'The skeletal system only', 'None: the body just uses stored energy'], answer: 'The respiratory and circulatory systems', why: 'Muscles need far more oxygen and glucose, so breathing and heart rate must rise.' },
  { km: 3, heart: 145, breaths: 32, tempC: 37.6, sweatL: 0.3, question: 'The runner’s heart rate has doubled. Why?', options: ['The heart is tired', 'To pump more blood carrying oxygen and glucose to the working muscles', 'Because blood is thicker', 'To cool the body'], answer: 'To pump more blood carrying oxygen and glucose to the working muscles', why: 'Working muscles respire faster and need more oxygen and glucose.' },
  { km: 8, heart: 160, breaths: 40, tempC: 38.2, sweatL: 0.9, question: 'Breathing is now 40 breaths a minute. What does faster, deeper breathing do?', options: ['Takes in more oxygen and removes more carbon dioxide', 'Cools the lungs', 'Makes the runner lighter', 'Stops sweating'], answer: 'Takes in more oxygen and removes more carbon dioxide', why: 'Respiration in muscle makes CO₂, which must be breathed out.' },
  { km: 12, heart: 165, breaths: 42, tempC: 38.6, sweatL: 1.4, question: 'The runner has lost 1.4 L of sweat. What should the medic advise at this water station?', options: ['Drink nothing until the finish', 'Drink water (with some salts)', 'Eat a big meal', 'Stop sweating on purpose'], answer: 'Drink water (with some salts)', why: 'Sweat removes water and salts; replacing them prevents dehydration.' },
  { km: 16, heart: 168, breaths: 42, tempC: 38.8, sweatL: 1.9, question: 'The runner hasn’t needed to urinate at all. Why?', options: ['The kidneys have stopped working', 'The kidneys are saving water because so much is lost as sweat', 'Running blocks the bladder', 'Urine turned into sweat'], answer: 'The kidneys are saving water because so much is lost as sweat', why: 'The kidneys reabsorb more water, making a small amount of concentrated urine.' },
  { km: 21, heart: 110, breaths: 24, tempC: 38.0, sweatL: 2.1, question: 'Just after finishing, heart and breathing rates are falling but still above resting. Why?', options: ['The body is repaying the oxygen needed to recover muscles', 'The runner is scared', 'The heart is broken', 'It is still the race'], answer: 'The body is repaying the oxygen needed to recover muscles', why: 'Extra oxygen is used to clear the lactic acid built up in hard-working muscles.' },
]
