export type Case = { id: string; patient: string; symptoms: string; answer: string; options: string[]; foods: string[]; why: string }

export const CASES: Case[] = [
  { id: 'scurvy', patient: 'A sailor on a long voyage', symptoms: 'Bleeding gums, wounds that heal very slowly, feeling tired.', answer: 'Vitamin C deficiency (scurvy)', options: ['Vitamin C deficiency (scurvy)', 'Iron deficiency (anaemia)', 'Iodine deficiency (goitre)', 'Protein deficiency'], foods: ['Amla', 'Guava', 'Oranges', 'Lemons'], why: 'Vitamin C keeps gums and skin healthy. Amla and guava are among the richest sources.' },
  { id: 'rickets', patient: 'A young child who rarely goes outdoors', symptoms: 'Soft, weak bones and bowed legs.', answer: 'Vitamin D and calcium deficiency (rickets)', options: ['Vitamin A deficiency', 'Vitamin D and calcium deficiency (rickets)', 'Vitamin C deficiency (scurvy)', 'Too much fat'], foods: ['Milk and curd', 'Ragi', 'Eggs', 'Morning sunlight (skin makes vitamin D)'], why: 'Vitamin D helps the body absorb calcium, which builds strong bones.' },
  { id: 'anaemia', patient: 'A teenager who feels tired and breathless', symptoms: 'Pale skin and inner eyelids, tiredness, breathlessness when climbing stairs.', answer: 'Iron deficiency (anaemia)', options: ['Iron deficiency (anaemia)', 'Iodine deficiency (goitre)', 'Vitamin D deficiency', 'Too much protein'], foods: ['Green leafy vegetables like palak', 'Jaggery', 'Dates', 'Rajma and chana', 'Eggs and meat'], why: 'Iron is needed to make haemoglobin, which carries oxygen in the blood. Eating it with vitamin C (like lemon) helps absorption.' },
  { id: 'nightblind', patient: 'A farmer in a village', symptoms: 'Can’t see well in dim light or at night.', answer: 'Vitamin A deficiency (night blindness)', options: ['Vitamin C deficiency', 'Vitamin A deficiency (night blindness)', 'Iron deficiency', 'Calcium deficiency'], foods: ['Carrots', 'Papaya and mango', 'Green leafy vegetables', 'Milk and eggs'], why: 'Vitamin A is needed for the eye to see in dim light.' },
  { id: 'goitre', patient: 'An adult in a hilly region', symptoms: 'A swelling at the front of the neck.', answer: 'Iodine deficiency (goitre)', options: ['Iodine deficiency (goitre)', 'Vitamin A deficiency', 'Protein deficiency', 'Iron deficiency'], foods: ['Iodised salt', 'Seafood'], why: 'The thyroid gland in the neck needs iodine. India made iodised salt widely available to prevent goitre.' },
  { id: 'protein', patient: 'A child whose diet is mostly rice and tea', symptoms: 'Very thin, poor growth, swollen belly and thin, discoloured hair.', answer: 'Protein and energy deficiency', options: ['Too much sugar', 'Protein and energy deficiency', 'Vitamin C deficiency', 'Iodine deficiency'], foods: ['Dal and pulses', 'Milk, curd and paneer', 'Eggs', 'Groundnuts'], why: 'Proteins are needed for growth and repair. Severe lack causes kwashiorkor and marasmus.' },
]
