export type Problem = { emoji: string; story: string; letter: string; options: string[]; answer: number; value: number; ask: string; unit: string; check: (v: number) => boolean }
export const PROBLEMS: Problem[] = [
  { emoji: '👦', story: 'Adam is 3 times as old as his sister. Their ages add up to 24.', letter: 's = sister’s age', options: ['s + 3s = 24', '3s = 24', 's + 3 = 24', '3(s + 24) = s'], answer: 0, value: 6, ask: 'How old is his sister?', unit: 'years', check: (s) => s + 3 * s === 24 },
  { emoji: '🔢', story: 'Three consecutive whole numbers add up to 81.', letter: 'n = the smallest number', options: ['n + (n + 1) + (n + 2) = 81', '3n = 81 + 3', 'n + n + n = 81', 'n(n + 1)(n + 2) = 81'], answer: 0, value: 26, ask: 'What is the smallest number?', unit: '', check: (n) => 3 * n + 3 === 81 },
  { emoji: '📐', story: 'A rectangle’s length is 5 cm more than its width. Its perimeter is 38 cm.', letter: 'w = width in cm', options: ['2(w + w + 5) = 38', 'w + w + 5 = 38', 'w(w + 5) = 38', '4w + 5 = 38'], answer: 0, value: 7, ask: 'What is the width?', unit: 'cm', check: (w) => 2 * (2 * w + 5) === 38 },
  { emoji: '🪙', story: 'Riya has 20 coins, all ₹10 or ₹5 coins. Together they are worth ₹140.', letter: 't = number of ₹10 coins', options: ['10t + 5(20 − t) = 140', '10t + 5t = 140', '15t = 140 − 20', '10t + 5 × 20 = 140'], answer: 0, value: 8, ask: 'How many ₹10 coins does she have?', unit: 'coins', check: (t) => 10 * t + 5 * (20 - t) === 140 },
  { emoji: '🛺', story: 'An auto-rickshaw charges ₹30 plus ₹15 per km. A ride costs ₹150.', letter: 'k = distance in km', options: ['30 + 15k = 150', '45k = 150', '15 + 30k = 150', '30k + 15k = 150'], answer: 0, value: 8, ask: 'How far was the ride?', unit: 'km', check: (k) => 30 + 15 * k === 150 },
  { emoji: '👛', story: 'After spending 2/5 of her pocket money, Meera has ₹180 left.', letter: 'm = pocket money in ₹', options: ['m − (2/5)m = 180', '(2/5)m = 180', 'm + (2/5)m = 180', 'm − 2/5 = 180'], answer: 0, value: 300, ask: 'How much pocket money did she have?', unit: '₹', check: (m) => m - (2 / 5) * m === 180 },
]
