/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubjectIndexRouteImport } from './routes/$subject/index'
import { Route as LabsIndexRouteImport } from './routes/labs/index'
import { Route as LabsLabIdRouteImport } from './routes/labs/$labId'
import { Route as SubjectUnitIndexRouteImport } from './routes/$subject/$unit/index'
import { Route as SubjectUnitTopicIndexRouteImport } from './routes/$subject/$unit/$topic/index'
import { Route as SubjectUnitTopicPracticeRouteImport } from './routes/$subject/$unit/$topic/practice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectIndexRoute = SubjectIndexRouteImport.update({
  id: '/$subject/',
  path: '/$subject/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsLabIdRoute = LabsLabIdRouteImport.update({
  id: '/labs/$labId',
  path: '/labs/$labId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectUnitIndexRoute = SubjectUnitIndexRouteImport.update({
  id: '/$subject/$unit/',
  path: '/$subject/$unit/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectUnitTopicIndexRoute = SubjectUnitTopicIndexRouteImport.update({
  id: '/$subject/$unit/$topic/',
  path: '/$subject/$unit/$topic/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectUnitTopicPracticeRoute =
  SubjectUnitTopicPracticeRouteImport.update({
    id: '/$subject/$unit/$topic/practice',
    path: '/$subject/$unit/$topic/practice',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/curriculum': typeof CurriculumRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/terms': typeof TermsRoute
  '/labs/$labId': typeof LabsLabIdRoute
  '/$subject/': typeof SubjectIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/$subject/$unit/': typeof SubjectUnitIndexRoute
  '/$subject/$unit/$topic/practice': typeof SubjectUnitTopicPracticeRoute
  '/$subject/$unit/$topic/': typeof SubjectUnitTopicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/curriculum': typeof CurriculumRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/terms': typeof TermsRoute
  '/labs/$labId': typeof LabsLabIdRoute
  '/$subject': typeof SubjectIndexRoute
  '/labs': typeof LabsIndexRoute
  '/$subject/$unit': typeof SubjectUnitIndexRoute
  '/$subject/$unit/$topic/practice': typeof SubjectUnitTopicPracticeRoute
  '/$subject/$unit/$topic': typeof SubjectUnitTopicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/curriculum': typeof CurriculumRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/terms': typeof TermsRoute
  '/labs/$labId': typeof LabsLabIdRoute
  '/$subject/': typeof SubjectIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/$subject/$unit/': typeof SubjectUnitIndexRoute
  '/$subject/$unit/$topic/practice': typeof SubjectUnitTopicPracticeRoute
  '/$subject/$unit/$topic/': typeof SubjectUnitTopicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/curriculum'
    | '/privacy'
    | '/progress'
    | '/review'
    | '/terms'
    | '/labs/$labId'
    | '/$subject/'
    | '/labs/'
    | '/$subject/$unit/'
    | '/$subject/$unit/$topic/practice'
    | '/$subject/$unit/$topic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/curriculum'
    | '/privacy'
    | '/progress'
    | '/review'
    | '/terms'
    | '/labs/$labId'
    | '/$subject'
    | '/labs'
    | '/$subject/$unit'
    | '/$subject/$unit/$topic/practice'
    | '/$subject/$unit/$topic'
  id:
    | '__root__'
    | '/'
    | '/curriculum'
    | '/privacy'
    | '/progress'
    | '/review'
    | '/terms'
    | '/labs/$labId'
    | '/$subject/'
    | '/labs/'
    | '/$subject/$unit/'
    | '/$subject/$unit/$topic/practice'
    | '/$subject/$unit/$topic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CurriculumRoute: typeof CurriculumRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  ReviewRoute: typeof ReviewRoute
  TermsRoute: typeof TermsRoute
  LabsLabIdRoute: typeof LabsLabIdRoute
  SubjectIndexRoute: typeof SubjectIndexRoute
  LabsIndexRoute: typeof LabsIndexRoute
  SubjectUnitIndexRoute: typeof SubjectUnitIndexRoute
  SubjectUnitTopicPracticeRoute: typeof SubjectUnitTopicPracticeRoute
  SubjectUnitTopicIndexRoute: typeof SubjectUnitTopicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$subject/': {
      id: '/$subject/'
      path: '/$subject'
      fullPath: '/$subject/'
      preLoaderRoute: typeof SubjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/$labId': {
      id: '/labs/$labId'
      path: '/labs/$labId'
      fullPath: '/labs/$labId'
      preLoaderRoute: typeof LabsLabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$subject/$unit/': {
      id: '/$subject/$unit/'
      path: '/$subject/$unit'
      fullPath: '/$subject/$unit/'
      preLoaderRoute: typeof SubjectUnitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$subject/$unit/$topic/': {
      id: '/$subject/$unit/$topic/'
      path: '/$subject/$unit/$topic'
      fullPath: '/$subject/$unit/$topic/'
      preLoaderRoute: typeof SubjectUnitTopicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$subject/$unit/$topic/practice': {
      id: '/$subject/$unit/$topic/practice'
      path: '/$subject/$unit/$topic/practice'
      fullPath: '/$subject/$unit/$topic/practice'
      preLoaderRoute: typeof SubjectUnitTopicPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CurriculumRoute: CurriculumRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  ReviewRoute: ReviewRoute,
  TermsRoute: TermsRoute,
  LabsLabIdRoute: LabsLabIdRoute,
  SubjectIndexRoute: SubjectIndexRoute,
  LabsIndexRoute: LabsIndexRoute,
  SubjectUnitIndexRoute: SubjectUnitIndexRoute,
  SubjectUnitTopicPracticeRoute: SubjectUnitTopicPracticeRoute,
  SubjectUnitTopicIndexRoute: SubjectUnitTopicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
