export type Task = { id: string; emoji: string; goal: string; options: string[]; answer: string; why: string }

export const TASKS: Task[] = [
  { id: 'potato', emoji: '🥔', goal: 'Grow a big potato crop quickly next season.', options: ['Plant pieces of potato, each with an “eye”', 'Plant potato leaves', 'Plant potato flowers', 'Wait for potato seeds to blow in'], answer: 'Plant pieces of potato, each with an “eye”', why: 'Each eye is a bud. Growing from tubers is fast and the plants are identical to the parent.' },
  { id: 'rose', emoji: '🌹', goal: 'Grow ten more rose bushes exactly like your prize-winning rose.', options: ['Take stem cuttings and plant them', 'Sow seeds from any rose', 'Plant a rose petal', 'Buy a different variety'], answer: 'Take stem cuttings and plant them', why: 'Vegetative propagation makes copies with the same features. Seeds would give mixed features.' },
  { id: 'pumpkin', emoji: '🎃', goal: 'Your pumpkin flowers bloom but few fruits form. The garden has no bees this year.', options: ['Hand-pollinate: brush pollen from male flowers onto female flowers', 'Water the flowers more', 'Pick off the petals', 'Add more fertiliser to the leaves'], answer: 'Hand-pollinate: brush pollen from male flowers onto female flowers', why: 'Without pollination there’s no fertilisation, and without fertilisation, no fruit.' },
  { id: 'bees', emoji: '🐝', goal: 'Make the garden more attractive to pollinators for next year.', options: ['Plant colourful, nectar-rich flowers and avoid harmful pesticides', 'Spray insecticide on the flowers', 'Plant only grass', 'Cover the plants with plastic'], answer: 'Plant colourful, nectar-rich flowers and avoid harmful pesticides', why: 'Bees need food (nectar and pollen) and are harmed by many pesticides.' },
  { id: 'drumstick', emoji: '🌳', goal: 'You want drumstick (moringa) trees to spread naturally across the windy hillside.', options: ['Let the winged seeds blow in the wind', 'Plant the seeds in a pot indoors', 'Remove the wings from the seeds', 'Bury the pods deeply'], answer: 'Let the winged seeds blow in the wind', why: 'Winged seeds are adapted for wind dispersal, which spreads them far from the parent.' },
  { id: 'crowding', emoji: '🌱', goal: 'Seedlings growing right under the parent tree are weak and thin. Why?', options: ['They compete with the parent for light, water and nutrients', 'The parent tree is poisoning them', 'They are too far apart', 'They have too much sunlight'], answer: 'They compete with the parent for light, water and nutrients', why: 'That’s why seed dispersal is so important for plants.' },
]
