import { lazy, type ComponentType, type LazyExoticComponent } from 'react'

export type LabInfo = {
  id: string
  title: string
  description: string
  subject: 'chemistry' | 'physics' | 'biology' | 'mathematics'
  emoji: string
  /** topic keys that use this lab */
  topics: string[]
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  component: LazyExoticComponent<ComponentType<any>>
}

export const LABS: LabInfo[] = [
  {
    id: 'matter-or-not',
    title: 'Matter or Not?',
    description: 'A quick card game: does it have mass and take up space?',
    subject: 'chemistry',
    emoji: '🃏',
    topics: ['chemistry/matter/what-is-matter'],
    component: lazy(() => import('./chemistry/matter-or-not/MatterOrNot')),
  },
  {
    id: 'particle-simulator',
    title: 'Particle Simulator',
    description: 'Heat and cool 5 substances. Watch particles and draw the heating curve.',
    subject: 'chemistry',
    emoji: '⚛️',
    topics: ['chemistry/matter/states-of-matter', 'chemistry/matter/changes-of-state'],
    component: lazy(() => import('./chemistry/particle-simulator/ParticleSimulator')),
  },
  {
    id: 'diffusion-race',
    title: 'Diffusion Race',
    description: 'Design a fair test: does temperature or medium make dye spread faster?',
    subject: 'chemistry',
    emoji: '🏁',
    topics: ['chemistry/matter/diffusion'],
    component: lazy(() => import('./chemistry/diffusion-race/DiffusionRace')),
  },
  {
    id: 'syringe-squeeze',
    title: 'Syringe Squeeze',
    description: 'Push sealed syringes of solid, liquid and gas. Which one squashes?',
    subject: 'chemistry',
    emoji: '💉',
    topics: ['chemistry/matter/forces-and-spaces'],
    component: lazy(() => import('./chemistry/syringe-squeeze/SyringeSqueeze')),
  },
  {
    id: 'density-tower',
    title: 'Density Tower',
    description: 'Calculate density, predict, and drop objects into oil, water and honey.',
    subject: 'chemistry',
    emoji: '🍯',
    topics: ['chemistry/matter/density'],
    component: lazy(() => import('./chemistry/density-tower/DensityTower')),
  },
  {
    id: 'particle-zoom',
    title: 'Particle Zoom',
    description: 'Zoom from a gold coin down to its atoms. Element, compound or mixture?',
    subject: 'chemistry',
    emoji: '🔬',
    topics: ['chemistry/mixtures/pure-substances-and-mixtures', 'chemistry/mixtures/elements-compounds-mixtures'],
    component: lazy(() => import('./chemistry/particle-zoom/ParticleZoom')),
  },
  {
    id: 'iron-sulfur',
    title: 'Iron + Sulfur',
    description: 'Mix, use a magnet, then heat. Watch a mixture become a compound.',
    subject: 'chemistry',
    emoji: '🧲',
    topics: ['chemistry/mixtures/elements-compounds-mixtures'],
    component: lazy(() => import('./chemistry/iron-sulfur/IronSulfur')),
  },
  {
    id: 'dissolving-lab',
    title: 'Dissolving Lab',
    description: 'Dissolve until saturated, draw a solubility curve, and grow crystals.',
    subject: 'chemistry',
    emoji: '🥄',
    topics: ['chemistry/mixtures/solutions-and-solubility', 'chemistry/mixtures/advanced-separation'],
    component: lazy(() => import('./chemistry/dissolving-lab/DissolvingLab')),
  },
  {
    id: 'separation-bench',
    title: 'Separation Bench',
    description: '7 mixture puzzles: pick the right tools, in the fewest steps.',
    subject: 'chemistry',
    emoji: '🧺',
    topics: ['chemistry/mixtures/everyday-separation'],
    component: lazy(() => import('./chemistry/separation-bench/SeparationBench')),
  },
  {
    id: 'chromatography',
    title: 'Chromatography Mystery',
    description: 'Separate the dyes in black ink to find who wrote the mystery note.',
    subject: 'chemistry',
    emoji: '🕵️',
    topics: ['chemistry/mixtures/advanced-separation'],
    component: lazy(() => import('./chemistry/chromatography/Chromatography')),
  },
  {
    id: 'distillation',
    title: 'Distillation',
    description: 'Boil, condense and collect pure water from salt water or inky water.',
    subject: 'chemistry',
    emoji: '⚗️',
    topics: ['chemistry/mixtures/advanced-separation'],
    component: lazy(() => import('./chemistry/distillation/Distillation')),
  },
  {
    id: 'village-well',
    title: 'Boss: Rescue the Village Well',
    description: 'Make muddy well water safe to drink, in the right order.',
    subject: 'chemistry',
    emoji: '🚰',
    topics: ['chemistry/mixtures/water-purification'],
    component: lazy(() => import('./chemistry/village-well/VillageWell')),
  },
  {
    id: 'change-detective',
    title: 'Change Detective',
    description: 'Physical, chemical or both? Solve 10 everyday cases.',
    subject: 'chemistry',
    emoji: '🕵️',
    topics: ['chemistry/changes/physical-and-chemical-changes'],
    component: lazy(() => import('./chemistry/change-detective/ChangeDetective')),
  },
  {
    id: 'reaction-bench',
    title: 'Reaction Bench',
    description: 'Mix substances, record the signs of a reaction, find all 7 reactions.',
    subject: 'chemistry',
    emoji: '🧪',
    topics: ['chemistry/changes/signs-of-a-reaction'],
    component: lazy(() => import('./chemistry/reaction-bench/ReactionBench')),
  },
  {
    id: 'rust-race',
    title: 'Rust Race',
    description: 'Six nails, six conditions, 10 days. What does rusting need?',
    subject: 'chemistry',
    emoji: '🔩',
    topics: ['chemistry/changes/rusting-and-corrosion'],
    component: lazy(() => import('./chemistry/rust-race/RustRace')),
  },
  {
    id: 'formula-builder',
    title: 'Formula Builder',
    description: 'Build molecules atom by atom: water, CO₂, methane, glucose…',
    subject: 'chemistry',
    emoji: '🧬',
    topics: ['chemistry/changes/symbols-formulas-equations'],
    component: lazy(() => import('./chemistry/formula-builder/FormulaBuilder')),
  },
  {
    id: 'mass-balance',
    title: 'Mass Balance',
    description: 'Predict: does mass go up, down or stay the same in a reaction?',
    subject: 'chemistry',
    emoji: '⚖️',
    topics: ['chemistry/changes/conservation-of-mass'],
    component: lazy(() => import('./chemistry/mass-balance/MassBalance')),
  },
  {
    id: 'fire-triangle',
    title: 'Fire Triangle',
    description: 'Put out a fire three ways, and time a candle under a jar.',
    subject: 'chemistry',
    emoji: '🔥',
    topics: ['chemistry/changes/combustion-and-flames'],
    component: lazy(() => import('./chemistry/fire-triangle/FireTriangle')),
  },
  {
    id: 'flame-explorer',
    title: 'Flame Explorer',
    description: 'Explore the three zones of a candle flame.',
    subject: 'chemistry',
    emoji: '🕯️',
    topics: ['chemistry/changes/combustion-and-flames'],
    component: lazy(() => import('./chemistry/flame-explorer/FlameExplorer')),
  },
  {
    id: 'refinery-tower',
    title: 'Refinery Tower',
    description: 'Build a crude oil refinery and compare fuel energy.',
    subject: 'chemistry',
    emoji: '🏭',
    topics: ['chemistry/changes/fuels'],
    component: lazy(() => import('./chemistry/refinery-tower/RefineryTower')),
  },
  {
    id: 'fire-safety',
    title: 'Boss: Fire Safety Officer',
    description: 'Six fire emergencies: choose the safe action every time.',
    subject: 'chemistry',
    emoji: '🧑‍🚒',
    topics: ['chemistry/changes/fire-safety'],
    component: lazy(() => import('./chemistry/fire-safety/FireSafety')),
  },
  {
    id: 'kitchen-hunt',
    title: 'Kitchen Acid Hunt',
    description: 'Test 13 kitchen and bathroom items with red and blue litmus.',
    subject: 'chemistry',
    emoji: '🍋',
    topics: ['chemistry/acids/acids-and-bases-around-us'],
    component: lazy(() => import('./chemistry/kitchen-hunt/KitchenHunt')),
  },
  {
    id: 'indicator-lab',
    title: 'Indicator Lab',
    description: 'A spotting tile: 7 indicators × 8 solutions. Find the patterns.',
    subject: 'chemistry',
    emoji: '🌈',
    topics: ['chemistry/acids/indicators'],
    component: lazy(() => import('./chemistry/indicator-lab/IndicatorLab')),
  },
  {
    id: 'ph-explorer',
    title: 'pH Explorer',
    description: 'Measure the pH of 19 substances and see what dilution does.',
    subject: 'chemistry',
    emoji: '📏',
    topics: ['chemistry/acids/ph-scale'],
    component: lazy(() => import('./chemistry/ph-explorer/PhExplorer')),
  },
  {
    id: 'neutralise-it',
    title: 'Neutralise It!',
    description: 'Titrate acid with base drop by drop and draw the pH curve.',
    subject: 'chemistry',
    emoji: '⚗️',
    topics: ['chemistry/acids/neutralisation'],
    component: lazy(() => import('./chemistry/neutralise-it/NeutraliseIt')),
  },
  {
    id: 'acid-reactions',
    title: 'Reactions of Acids',
    description: 'Acids + metals and carbonates. Identify the gas with the pop test.',
    subject: 'chemistry',
    emoji: '💥',
    topics: ['chemistry/acids/reactions-of-acids'],
    component: lazy(() => import('./chemistry/acid-reactions/AcidReactions')),
  },
  {
    id: 'acid-rain',
    title: 'Acid Rain Simulator',
    description: 'Pollution, rain pH, a marble monument and a lake. Can you fix it?',
    subject: 'chemistry',
    emoji: '☔',
    topics: ['chemistry/acids/acid-rain'],
    component: lazy(() => import('./chemistry/acid-rain/AcidRain')),
  },
  {
    id: 'mystery-bottles',
    title: 'Boss: The Mystery Bottles',
    description: 'Identify six unlabelled bottles with as few tests as possible.',
    subject: 'chemistry',
    emoji: '🕵️',
    topics: ['chemistry/acids/mystery-bottles'],
    component: lazy(() => import('./chemistry/mystery-bottles/MysteryBottles')),
  },
  {
    id: 'property-tester',
    title: 'Property Tester',
    description: 'Hammer, wire up, drop and scratch 7 materials. Spot the exceptions!',
    subject: 'chemistry',
    emoji: '🔨',
    topics: ['chemistry/metals/properties-of-metals-and-non-metals'],
    component: lazy(() => import('./chemistry/property-tester/PropertyTester')),
  },
  {
    id: 'metal-reactions',
    title: 'Metal Reactions',
    description: '8 metals × oxygen, water and acid. Build a reactivity league table.',
    subject: 'chemistry',
    emoji: '🔥',
    topics: ['chemistry/metals/reactions-of-metals'],
    component: lazy(() => import('./chemistry/metal-reactions/MetalReactions')),
  },
  {
    id: 'displacement-duel',
    title: 'Displacement Duel',
    description: 'Predict and test 20 metal + salt solution pairs. Find the reactivity series.',
    subject: 'chemistry',
    emoji: '⚔️',
    topics: ['chemistry/metals/reactivity-series'],
    component: lazy(() => import('./chemistry/displacement-duel/DisplacementDuel')),
  },
  {
    id: 'alloy-workshop',
    title: 'Alloy Workshop',
    description: 'Mix metals to discover steel, brass, bronze, solder and 22-carat gold.',
    subject: 'chemistry',
    emoji: '🪙',
    topics: ['chemistry/metals/alloys'],
    component: lazy(() => import('./chemistry/alloy-workshop/AlloyWorkshop')),
  },
  {
    id: 'plastic-timeline',
    title: 'How Long Does It Last?',
    description: 'Order 8 items by how long they take to break down in nature.',
    subject: 'chemistry',
    emoji: '🧴',
    topics: ['chemistry/metals/plastics-and-synthetic-materials'],
    component: lazy(() => import('./chemistry/plastic-timeline/PlasticTimeline')),
  },
  {
    id: 'electroplating',
    title: 'Electricity in Liquids',
    description: 'Which liquids conduct? Then copper-plate an iron key.',
    subject: 'chemistry',
    emoji: '🔑',
    topics: ['chemistry/metals/electroplating'],
    component: lazy(() => import('./chemistry/electroplating/Electroplating')),
  },
  {
    id: 'materials-engineer',
    title: 'Boss: Materials Engineer',
    description: 'Choose the best material for six real engineering jobs.',
    subject: 'chemistry',
    emoji: '👷',
    topics: ['chemistry/metals/materials-engineer'],
    component: lazy(() => import('./chemistry/materials-engineer/MaterialsEngineer')),
  },
]

export const getLab = (id: string) => LABS.find((l) => l.id === id)
