import { lazy, type ComponentType, type LazyExoticComponent } from 'react'

export type LabInfo = {
  id: string
  title: string
  description: string
  subject: 'chemistry' | 'physics' | 'biology' | 'mathematics'
  emoji: string
  /** topic keys that use this lab */
  topics: string[]
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  component: LazyExoticComponent<ComponentType<any>>
}

export const LABS: LabInfo[] = [
  {
    id: 'matter-or-not',
    title: 'Matter or Not?',
    description: 'A quick card game: does it have mass and take up space?',
    subject: 'chemistry',
    emoji: '🃏',
    topics: ['chemistry/matter/what-is-matter'],
    component: lazy(() => import('./chemistry/matter-or-not/MatterOrNot')),
  },
  {
    id: 'particle-simulator',
    title: 'Particle Simulator',
    description: 'Heat and cool 5 substances. Watch particles and draw the heating curve.',
    subject: 'chemistry',
    emoji: '⚛️',
    topics: ['chemistry/matter/states-of-matter', 'chemistry/matter/changes-of-state'],
    component: lazy(() => import('./chemistry/particle-simulator/ParticleSimulator')),
  },
  {
    id: 'diffusion-race',
    title: 'Diffusion Race',
    description: 'Design a fair test: does temperature or medium make dye spread faster?',
    subject: 'chemistry',
    emoji: '🏁',
    topics: ['chemistry/matter/diffusion'],
    component: lazy(() => import('./chemistry/diffusion-race/DiffusionRace')),
  },
  {
    id: 'syringe-squeeze',
    title: 'Syringe Squeeze',
    description: 'Push sealed syringes of solid, liquid and gas. Which one squashes?',
    subject: 'chemistry',
    emoji: '💉',
    topics: ['chemistry/matter/forces-and-spaces'],
    component: lazy(() => import('./chemistry/syringe-squeeze/SyringeSqueeze')),
  },
  {
    id: 'density-tower',
    title: 'Density Tower',
    description: 'Calculate density, predict, and drop objects into oil, water and honey.',
    subject: 'chemistry',
    emoji: '🍯',
    topics: ['chemistry/matter/density'],
    component: lazy(() => import('./chemistry/density-tower/DensityTower')),
  },
  {
    id: 'particle-zoom',
    title: 'Particle Zoom',
    description: 'Zoom from a gold coin down to its atoms. Element, compound or mixture?',
    subject: 'chemistry',
    emoji: '🔬',
    topics: ['chemistry/mixtures/pure-substances-and-mixtures', 'chemistry/mixtures/elements-compounds-mixtures'],
    component: lazy(() => import('./chemistry/particle-zoom/ParticleZoom')),
  },
  {
    id: 'iron-sulfur',
    title: 'Iron + Sulfur',
    description: 'Mix, use a magnet, then heat. Watch a mixture become a compound.',
    subject: 'chemistry',
    emoji: '🧲',
    topics: ['chemistry/mixtures/elements-compounds-mixtures'],
    component: lazy(() => import('./chemistry/iron-sulfur/IronSulfur')),
  },
  {
    id: 'dissolving-lab',
    title: 'Dissolving Lab',
    description: 'Dissolve until saturated, draw a solubility curve, and grow crystals.',
    subject: 'chemistry',
    emoji: '🥄',
    topics: ['chemistry/mixtures/solutions-and-solubility', 'chemistry/mixtures/advanced-separation'],
    component: lazy(() => import('./chemistry/dissolving-lab/DissolvingLab')),
  },
  {
    id: 'separation-bench',
    title: 'Separation Bench',
    description: '7 mixture puzzles: pick the right tools, in the fewest steps.',
    subject: 'chemistry',
    emoji: '🧺',
    topics: ['chemistry/mixtures/everyday-separation'],
    component: lazy(() => import('./chemistry/separation-bench/SeparationBench')),
  },
  {
    id: 'chromatography',
    title: 'Chromatography Mystery',
    description: 'Separate the dyes in black ink to find who wrote the mystery note.',
    subject: 'chemistry',
    emoji: '🕵️',
    topics: ['chemistry/mixtures/advanced-separation'],
    component: lazy(() => import('./chemistry/chromatography/Chromatography')),
  },
  {
    id: 'distillation',
    title: 'Distillation',
    description: 'Boil, condense and collect pure water from salt water or inky water.',
    subject: 'chemistry',
    emoji: '⚗️',
    topics: ['chemistry/mixtures/advanced-separation'],
    component: lazy(() => import('./chemistry/distillation/Distillation')),
  },
  {
    id: 'village-well',
    title: 'Boss: Rescue the Village Well',
    description: 'Make muddy well water safe to drink, in the right order.',
    subject: 'chemistry',
    emoji: '🚰',
    topics: ['chemistry/mixtures/water-purification'],
    component: lazy(() => import('./chemistry/village-well/VillageWell')),
  },
  {
    id: 'change-detective',
    title: 'Change Detective',
    description: 'Physical, chemical or both? Solve 10 everyday cases.',
    subject: 'chemistry',
    emoji: '🕵️',
    topics: ['chemistry/changes/physical-and-chemical-changes'],
    component: lazy(() => import('./chemistry/change-detective/ChangeDetective')),
  },
  {
    id: 'reaction-bench',
    title: 'Reaction Bench',
    description: 'Mix substances, record the signs of a reaction, find all 7 reactions.',
    subject: 'chemistry',
    emoji: '🧪',
    topics: ['chemistry/changes/signs-of-a-reaction'],
    component: lazy(() => import('./chemistry/reaction-bench/ReactionBench')),
  },
  {
    id: 'rust-race',
    title: 'Rust Race',
    description: 'Six nails, six conditions, 10 days. What does rusting need?',
    subject: 'chemistry',
    emoji: '🔩',
    topics: ['chemistry/changes/rusting-and-corrosion'],
    component: lazy(() => import('./chemistry/rust-race/RustRace')),
  },
  {
    id: 'formula-builder',
    title: 'Formula Builder',
    description: 'Build molecules atom by atom: water, CO₂, methane, glucose…',
    subject: 'chemistry',
    emoji: '🧬',
    topics: ['chemistry/changes/symbols-formulas-equations'],
    component: lazy(() => import('./chemistry/formula-builder/FormulaBuilder')),
  },
  {
    id: 'mass-balance',
    title: 'Mass Balance',
    description: 'Predict: does mass go up, down or stay the same in a reaction?',
    subject: 'chemistry',
    emoji: '⚖️',
    topics: ['chemistry/changes/conservation-of-mass'],
    component: lazy(() => import('./chemistry/mass-balance/MassBalance')),
  },
  {
    id: 'fire-triangle',
    title: 'Fire Triangle',
    description: 'Put out a fire three ways, and time a candle under a jar.',
    subject: 'chemistry',
    emoji: '🔥',
    topics: ['chemistry/changes/combustion-and-flames'],
    component: lazy(() => import('./chemistry/fire-triangle/FireTriangle')),
  },
  {
    id: 'flame-explorer',
    title: 'Flame Explorer',
    description: 'Explore the three zones of a candle flame.',
    subject: 'chemistry',
    emoji: '🕯️',
    topics: ['chemistry/changes/combustion-and-flames'],
    component: lazy(() => import('./chemistry/flame-explorer/FlameExplorer')),
  },
  {
    id: 'refinery-tower',
    title: 'Refinery Tower',
    description: 'Build a crude oil refinery and compare fuel energy.',
    subject: 'chemistry',
    emoji: '🏭',
    topics: ['chemistry/changes/fuels'],
    component: lazy(() => import('./chemistry/refinery-tower/RefineryTower')),
  },
  {
    id: 'fire-safety',
    title: 'Boss: Fire Safety Officer',
    description: 'Six fire emergencies: choose the safe action every time.',
    subject: 'chemistry',
    emoji: '🧑‍🚒',
    topics: ['chemistry/changes/fire-safety'],
    component: lazy(() => import('./chemistry/fire-safety/FireSafety')),
  },
  {
    id: 'kitchen-hunt',
    title: 'Kitchen Acid Hunt',
    description: 'Test 13 kitchen and bathroom items with red and blue litmus.',
    subject: 'chemistry',
    emoji: '🍋',
    topics: ['chemistry/acids/acids-and-bases-around-us'],
    component: lazy(() => import('./chemistry/kitchen-hunt/KitchenHunt')),
  },
  {
    id: 'indicator-lab',
    title: 'Indicator Lab',
    description: 'A spotting tile: 7 indicators × 8 solutions. Find the patterns.',
    subject: 'chemistry',
    emoji: '🌈',
    topics: ['chemistry/acids/indicators'],
    component: lazy(() => import('./chemistry/indicator-lab/IndicatorLab')),
  },
  {
    id: 'ph-explorer',
    title: 'pH Explorer',
    description: 'Measure the pH of 19 substances and see what dilution does.',
    subject: 'chemistry',
    emoji: '📏',
    topics: ['chemistry/acids/ph-scale'],
    component: lazy(() => import('./chemistry/ph-explorer/PhExplorer')),
  },
  {
    id: 'neutralise-it',
    title: 'Neutralise It!',
    description: 'Titrate acid with base drop by drop and draw the pH curve.',
    subject: 'chemistry',
    emoji: '⚗️',
    topics: ['chemistry/acids/neutralisation'],
    component: lazy(() => import('./chemistry/neutralise-it/NeutraliseIt')),
  },
  {
    id: 'acid-reactions',
    title: 'Reactions of Acids',
    description: 'Acids + metals and carbonates. Identify the gas with the pop test.',
    subject: 'chemistry',
    emoji: '💥',
    topics: ['chemistry/acids/reactions-of-acids'],
    component: lazy(() => import('./chemistry/acid-reactions/AcidReactions')),
  },
  {
    id: 'acid-rain',
    title: 'Acid Rain Simulator',
    description: 'Pollution, rain pH, a marble monument and a lake. Can you fix it?',
    subject: 'chemistry',
    emoji: '☔',
    topics: ['chemistry/acids/acid-rain'],
    component: lazy(() => import('./chemistry/acid-rain/AcidRain')),
  },
  {
    id: 'mystery-bottles',
    title: 'Boss: The Mystery Bottles',
    description: 'Identify six unlabelled bottles with as few tests as possible.',
    subject: 'chemistry',
    emoji: '🕵️',
    topics: ['chemistry/acids/mystery-bottles'],
    component: lazy(() => import('./chemistry/mystery-bottles/MysteryBottles')),
  },
  {
    id: 'property-tester',
    title: 'Property Tester',
    description: 'Hammer, wire up, drop and scratch 7 materials. Spot the exceptions!',
    subject: 'chemistry',
    emoji: '🔨',
    topics: ['chemistry/metals/properties-of-metals-and-non-metals'],
    component: lazy(() => import('./chemistry/property-tester/PropertyTester')),
  },
  {
    id: 'metal-reactions',
    title: 'Metal Reactions',
    description: '8 metals × oxygen, water and acid. Build a reactivity league table.',
    subject: 'chemistry',
    emoji: '🔥',
    topics: ['chemistry/metals/reactions-of-metals'],
    component: lazy(() => import('./chemistry/metal-reactions/MetalReactions')),
  },
  {
    id: 'displacement-duel',
    title: 'Displacement Duel',
    description: 'Predict and test 20 metal + salt solution pairs. Find the reactivity series.',
    subject: 'chemistry',
    emoji: '⚔️',
    topics: ['chemistry/metals/reactivity-series'],
    component: lazy(() => import('./chemistry/displacement-duel/DisplacementDuel')),
  },
  {
    id: 'alloy-workshop',
    title: 'Alloy Workshop',
    description: 'Mix metals to discover steel, brass, bronze, solder and 22-carat gold.',
    subject: 'chemistry',
    emoji: '🪙',
    topics: ['chemistry/metals/alloys'],
    component: lazy(() => import('./chemistry/alloy-workshop/AlloyWorkshop')),
  },
  {
    id: 'plastic-timeline',
    title: 'How Long Does It Last?',
    description: 'Order 8 items by how long they take to break down in nature.',
    subject: 'chemistry',
    emoji: '🧴',
    topics: ['chemistry/metals/plastics-and-synthetic-materials'],
    component: lazy(() => import('./chemistry/plastic-timeline/PlasticTimeline')),
  },
  {
    id: 'electroplating',
    title: 'Electricity in Liquids',
    description: 'Which liquids conduct? Then copper-plate an iron key.',
    subject: 'chemistry',
    emoji: '🔑',
    topics: ['chemistry/metals/electroplating'],
    component: lazy(() => import('./chemistry/electroplating/Electroplating')),
  },
  {
    id: 'materials-engineer',
    title: 'Boss: Materials Engineer',
    description: 'Choose the best material for six real engineering jobs.',
    subject: 'chemistry',
    emoji: '👷',
    topics: ['chemistry/metals/materials-engineer'],
    component: lazy(() => import('./chemistry/materials-engineer/MaterialsEngineer')),
  },
  {
    id: 'gold-foil',
    title: 'Rutherford\'s Gold Foil',
    description: 'Fire alpha particles at gold foil and discover the nucleus.',
    subject: 'chemistry',
    emoji: '🥇',
    topics: ['chemistry/atoms/history-of-the-atom'],
    component: lazy(() => import('./chemistry/gold-foil/GoldFoil')),
  },
  {
    id: 'atom-builder',
    title: 'Atom Builder',
    description: 'Build atoms, ions and isotopes from protons, neutrons and electrons.',
    subject: 'chemistry',
    emoji: '⚛️',
    topics: ['chemistry/atoms/inside-the-atom', 'chemistry/atoms/isotopes'],
    component: lazy(() => import('./chemistry/atom-builder/AtomBuilder')),
  },
  {
    id: 'shell-builder',
    title: 'Shell Builder',
    description: 'Arrange electrons into shells: 2, 8, 8.',
    subject: 'chemistry',
    emoji: '🎯',
    topics: ['chemistry/atoms/electron-shells'],
    component: lazy(() => import('./chemistry/shell-builder/ShellBuilder')),
  },
  {
    id: 'periodic-explorer',
    title: 'Periodic Table Explorer',
    description: 'Explore and collect the first 20 elements, and complete quests.',
    subject: 'chemistry',
    emoji: '🗂️',
    topics: ['chemistry/atoms/periodic-table'],
    component: lazy(() => import('./chemistry/periodic-explorer/PeriodicExplorer')),
  },
  {
    id: 'element-families',
    title: 'Element Families',
    description: 'Alkali metals in water, halogen colours and glowing noble gases.',
    subject: 'chemistry',
    emoji: '👨‍👩‍👧',
    topics: ['chemistry/atoms/element-families'],
    component: lazy(() => import('./chemistry/element-families/ElementFamilies')),
  },
  {
    id: 'element-detective',
    title: 'Boss: Element Detective',
    description: 'Identify 8 mystery elements from clues on the periodic table.',
    subject: 'chemistry',
    emoji: '🔎',
    topics: ['chemistry/atoms/element-detective'],
    component: lazy(() => import('./chemistry/element-detective/ElementDetective')),
  },
  {
    id: 'measure-it',
    title: 'Measure It!',
    description: 'The handspan problem, reading a ruler (even a broken one) and parallax error.',
    subject: 'physics',
    emoji: '📏',
    topics: ['physics/motion/measurement'],
    component: lazy(() => import('./physics/measure-it/MeasureIt')),
  },
  {
    id: 'motion-sorter',
    title: 'Motion Sorter',
    description: 'Linear, circular or oscillatory? Classify moving things.',
    subject: 'physics',
    emoji: '🎡',
    topics: ['physics/motion/types-of-motion'],
    component: lazy(() => import('./physics/motion-sorter/MotionSorter')),
  },
  {
    id: 'race-track',
    title: 'Race Track',
    description: 'Race Adam, a cheetah, an auto and a Vande Bharat train. Calculate speeds.',
    subject: 'physics',
    emoji: '🏁',
    topics: ['physics/motion/speed'],
    component: lazy(() => import('./physics/race-track/RaceTrack')),
  },
  {
    id: 'graph-walker',
    title: 'Graph Walker',
    description: 'Program a walk and match its distance-time graph to a target.',
    subject: 'physics',
    emoji: '📈',
    topics: ['physics/motion/distance-time-graphs'],
    component: lazy(() => import('./physics/graph-walker/GraphWalker')),
  },
  {
    id: 'pendulum-lab',
    title: 'Pendulum Lab',
    description: 'Time the swings and find what really changes a pendulum\'s period.',
    subject: 'physics',
    emoji: '🕰️',
    topics: ['physics/motion/time-and-pendulums'],
    component: lazy(() => import('./physics/pendulum-lab/PendulumLab')),
  },
  {
    id: 'bengaluru-race',
    title: 'Boss: The Great Bengaluru Race',
    description: 'Read a four-traveller distance-time graph from Majestic to Whitefield.',
    subject: 'physics',
    emoji: '🚇',
    topics: ['physics/motion/great-bengaluru-race'],
    component: lazy(() => import('./physics/bengaluru-race/BengaluruRace')),
  },
  {
    id: 'force-playground',
    title: 'Force Playground',
    description: 'Balanced and unbalanced forces: two teams push a heavy box, on a rough floor or on ice.',
    subject: 'physics',
    emoji: '💪',
    topics: ['physics/forces/pushes-and-pulls'],
    component: lazy(() => import('./physics/force-playground/ForcePlayground')),
  },
  {
    id: 'invisible-forces',
    title: 'Invisible Forces',
    description: 'Magnets that attract and repel, a charged balloon, and a falling mango.',
    subject: 'physics',
    emoji: '🧲',
    topics: ['physics/forces/contact-and-non-contact-forces'],
    component: lazy(() => import('./physics/invisible-forces/InvisibleForces')),
  },
  {
    id: 'friction-ramp',
    title: 'Friction Ramp',
    description: 'Tilt a ramp of ice, glass, wood, carpet or sandpaper until the block slides.',
    subject: 'physics',
    emoji: '🛝',
    topics: ['physics/forces/friction'],
    component: lazy(() => import('./physics/friction-ramp/FrictionRamp')),
  },
  {
    id: 'planet-scales',
    title: 'Planet Scales',
    description: 'Your weight on the Moon, Mars and Jupiter, plus the hammer-and-feather drop.',
    subject: 'physics',
    emoji: '🪐',
    topics: ['physics/forces/gravity-and-weight'],
    component: lazy(() => import('./physics/planet-scales/PlanetScales')),
  },
  {
    id: 'pressure-lab',
    title: 'Pressure Lab',
    description: 'Stilettos vs snowshoes on soft snow, and the bed of nails.',
    subject: 'physics',
    emoji: '👠',
    topics: ['physics/forces/pressure'],
    component: lazy(() => import('./physics/pressure-lab/PressureLab')),
  },
  {
    id: 'liquid-pressure',
    title: 'Pressure in Liquids and Air',
    description: 'Water jets from a tank, and a can crushed by the air.',
    subject: 'physics',
    emoji: '💧',
    topics: ['physics/forces/pressure-in-liquids-and-air'],
    component: lazy(() => import('./physics/liquid-pressure/LiquidPressure')),
  },
  {
    id: 'cyclone-lab',
    title: 'Winds, Storms and Cyclones',
    description: 'Sea and land breezes, and grow a cyclone over the Bay of Bengal.',
    subject: 'physics',
    emoji: '🌀',
    topics: ['physics/forces/winds-and-cyclones'],
    component: lazy(() => import('./physics/cyclone-lab/CycloneLab')),
  },
  {
    id: 'force-fixers',
    title: 'Boss: Force Fixers',
    description: 'Fix eight real problems using forces, friction and pressure.',
    subject: 'physics',
    emoji: '🛠️',
    topics: ['physics/forces/force-fixers'],
    component: lazy(() => import('./physics/force-fixers/ForceFixers')),
  },
  {
    id: 'energy-chain',
    title: 'Energy Chain',
    description: 'Build chains of devices that change energy from one form to another, from sunshine to a spinning fan.',
    subject: 'physics',
    emoji: '⚡',
    topics: ['physics/energy/forms-of-energy'],
    component: lazy(() => import('./physics/energy-chain/EnergyChain')),
  },
  {
    id: 'heat-mixer',
    title: 'Heat Mixer',
    description: 'Mix hot and cold water, and find out why a bucket of warm water holds more heat than a cup of hot water.',
    subject: 'physics',
    emoji: '🥛',
    topics: ['physics/energy/heat-and-temperature'],
    component: lazy(() => import('./physics/heat-mixer/HeatMixer')),
  },
  {
    id: 'thermometer-lab',
    title: 'Thermometer Lab',
    description: 'Choose the right thermometer, read the scale, and convert between °C, °F and K.',
    subject: 'physics',
    emoji: '🌡️',
    topics: ['physics/energy/measuring-temperature'],
    component: lazy(() => import('./physics/thermometer-lab/ThermometerLab')),
  },
  {
    id: 'heat-flow',
    title: 'Heat Flow: The Spoon Race',
    description: 'Race spoons of silver, copper, steel, glass, wood and plastic in hot chai.',
    subject: 'physics',
    emoji: '🥄',
    topics: ['physics/energy/conduction'],
    component: lazy(() => import('./physics/heat-flow/HeatFlow')),
  },
  {
    id: 'convection-radiation',
    title: 'Convection and Radiation',
    description: 'Watch convection currents in a pot, and compare black, white and shiny cans under a lamp.',
    subject: 'physics',
    emoji: '🌀',
    topics: ['physics/energy/convection-and-radiation'],
    component: lazy(() => import('./physics/convection-radiation/ConvectionRadiation')),
  },
  {
    id: 'flask-lab',
    title: 'Flask Lab',
    description: 'Keep chai hot and water cool: flasks, kulhads, thermocol and the clay matka.',
    subject: 'physics',
    emoji: '🧴',
    topics: ['physics/energy/keeping-hot-and-cold'],
    component: lazy(() => import('./physics/flask-lab/FlaskLab')),
  },
  {
    id: 'cool-house',
    title: 'Boss: Cool House',
    description: 'Design homes that stay comfortable in a Chennai summer and a Delhi winter.',
    subject: 'physics',
    emoji: '🏡',
    topics: ['physics/energy/cool-house'],
    component: lazy(() => import('./physics/cool-house/CoolHouse')),
  },
  {
    id: 'shadow-theatre',
    title: 'Shadow Theatre',
    description: 'Make shadows grow and shrink, test transparent, translucent and opaque materials, and build a pinhole camera.',
    subject: 'physics',
    emoji: '🎭',
    topics: ['physics/light/light-and-shadows'],
    component: lazy(() => import('./physics/shadow-theatre/ShadowTheatre')),
  },
  {
    id: 'reflection-lab',
    title: 'Reflection Lab',
    description: 'Shine a laser at a mirror, measure the angles, and compare regular and diffuse reflection.',
    subject: 'physics',
    emoji: '🔦',
    topics: ['physics/light/reflection'],
    component: lazy(() => import('./physics/reflection-lab/ReflectionLab')),
  },
  {
    id: 'mirror-images',
    title: 'Mirror Images',
    description: 'Mirror writing, image distance in a plane mirror, and a periscope you angle yourself.',
    subject: 'physics',
    emoji: '🪞',
    topics: ['physics/light/plane-mirrors'],
    component: lazy(() => import('./physics/mirror-images/MirrorImages')),
  },
  {
    id: 'optics-bench',
    title: 'Optics Bench',
    description: 'Trace rays through concave and convex mirrors and lenses, and find where the image forms.',
    subject: 'physics',
    emoji: '🔍',
    topics: ['physics/light/curved-mirrors', 'physics/light/lenses'],
    component: lazy(() => import('./physics/optics-bench/OpticsBench')),
  },
  {
    id: 'prism-lab',
    title: 'Prism and Colour Lab',
    description: 'Split white light into VIBGYOR, recombine it with a second prism, and spin Newton\'s colour disc.',
    subject: 'physics',
    emoji: '🌈',
    topics: ['physics/light/colours-of-light'],
    component: lazy(() => import('./physics/prism-lab/PrismLab')),
  },
  {
    id: 'laser-maze',
    title: 'Boss: Laser Maze',
    description: 'Place mirrors to steer a laser onto every target, over five levels.',
    subject: 'physics',
    emoji: '🎯',
    topics: ['physics/light/laser-maze'],
    component: lazy(() => import('./physics/laser-maze/LaserMaze')),
  },
  {
    id: 'vibration-lab',
    title: 'Vibration Lab',
    description: 'Twang a ruler and find what vibrates in a tabla, veena, bansuri and your own voice.',
    subject: 'physics',
    emoji: '📏',
    topics: ['physics/sound/vibrations'],
    component: lazy(() => import('./physics/vibration-lab/VibrationLab')),
  },
  {
    id: 'sound-travel',
    title: 'How Sound Travels',
    description: 'Watch particles pass a sound along, race sound through air, water and steel, pump out a bell jar and time echoes.',
    subject: 'physics',
    emoji: '🔔',
    topics: ['physics/sound/how-sound-travels'],
    component: lazy(() => import('./physics/sound-travel/SoundTravel')),
  },
  {
    id: 'wave-maker',
    title: 'Wave Maker',
    description: 'Hear and see how frequency sets pitch and amplitude sets loudness, and which animals can hear each sound.',
    subject: 'physics',
    emoji: '〰️',
    topics: ['physics/sound/pitch-and-loudness'],
    component: lazy(() => import('./physics/wave-maker/WaveMaker')),
  },
  {
    id: 'music-lab',
    title: 'Music Lab',
    description: 'Tune a jal tarang to the sargam, pluck a veena string, and solve the bottle puzzle.',
    subject: 'physics',
    emoji: '🎶',
    topics: ['physics/sound/musical-instruments'],
    component: lazy(() => import('./physics/music-lab/MusicLab')),
  },
  {
    id: 'noise-lab',
    title: 'Noise Lab',
    description: 'The decibel ladder, safe listening times, India\'s noise rules and an optional loudness meter.',
    subject: 'physics',
    emoji: '🔊',
    topics: ['physics/sound/hearing-and-noise'],
    component: lazy(() => import('./physics/noise-lab/NoiseLab')),
  },
  {
    id: 'sonar-mapper',
    title: 'Boss: Sonar Mapper',
    description: 'Use echo times to map the seabed and find a sunken ship.',
    subject: 'physics',
    emoji: '🚢',
    topics: ['physics/sound/sonar-mapper'],
    component: lazy(() => import('./physics/sonar-mapper/SonarMapper')),
  },
  {
    id: 'magnet-lab',
    title: 'Magnet Lab',
    description: 'Test which materials are magnetic, map a magnet\'s field with compasses and iron filings, and see why compasses point north.',
    subject: 'physics',
    emoji: '🧲',
    topics: ['physics/electricity/magnets'],
    component: lazy(() => import('./physics/magnet-lab/MagnetLab')),
  },
  {
    id: 'circuit-builder',
    title: 'Circuit Builder',
    description: 'Build circuits with cells, bulbs, LEDs and switches, test conductors and insulators, and compare series and parallel.',
    subject: 'physics',
    emoji: '🔌',
    topics: ['physics/electricity/electric-circuits', 'physics/electricity/conductors-and-insulators'],
    component: lazy(() => import('./physics/circuit-builder/CircuitBuilder')),
  },
  {
    id: 'heating-effect',
    title: 'Heating Effect of Current',
    description: 'See why nichrome glows while copper stays cool, and overload a home\'s fuse box.',
    subject: 'physics',
    emoji: '🔥',
    topics: ['physics/electricity/heating-effect'],
    component: lazy(() => import('./physics/heating-effect/HeatingEffect')),
  },
  {
    id: 'electromagnet-lab',
    title: 'Electromagnet Lab',
    description: 'Repeat Ørsted\'s compass discovery and build an electromagnet that lifts paper clips.',
    subject: 'physics',
    emoji: '🧷',
    topics: ['physics/electricity/electromagnets'],
    component: lazy(() => import('./physics/electromagnet-lab/ElectromagnetLab')),
  },
  {
    id: 'circuit-detective',
    title: 'Boss: Circuit Detective',
    description: 'Diagnose and fix seven broken circuits.',
    subject: 'physics',
    emoji: '🕵️',
    topics: ['physics/electricity/circuit-detective'],
    component: lazy(() => import('./physics/circuit-detective/CircuitDetective')),
  },
  {
    id: 'day-night',
    title: 'Day, Night and the Moving Sun',
    description: 'Spin the Earth to see day and night, and track a stick\'s shadow through the day.',
    subject: 'physics',
    emoji: '🌍',
    topics: ['physics/space/day-and-night'],
    component: lazy(() => import('./physics/day-night/DayNight')),
  },
  {
    id: 'seasons-lab',
    title: 'Seasons Lab',
    description: 'See how Earth\'s tilt, not its distance, causes the seasons, with day lengths from Bengaluru to the Arctic.',
    subject: 'physics',
    emoji: '🌦️',
    topics: ['physics/space/seasons'],
    component: lazy(() => import('./physics/seasons-lab/SeasonsLab')),
  },
  {
    id: 'moon-lab',
    title: 'Moon Lab',
    description: 'Watch the Moon\'s phases from space and from India, and discover when eclipses happen.',
    subject: 'physics',
    emoji: '🌓',
    topics: ['physics/space/moon-phases-and-eclipses'],
    component: lazy(() => import('./physics/moon-lab/MoonLab')),
  },
  {
    id: 'sky-calendar',
    title: 'Sky Calendar',
    description: 'Solar, lunar and lunisolar calendars: why Makar Sankranti stays put, Diwali shifts a little and Eid moves round the year.',
    subject: 'physics',
    emoji: '📅',
    topics: ['physics/space/keeping-time'],
    component: lazy(() => import('./physics/sky-calendar/SkyCalendar')),
  },
  {
    id: 'solar-system',
    title: 'Solar System Explorer',
    description: 'Orbiting planets with facts, and a scale model of the Solar System with a football-sized Sun.',
    subject: 'physics',
    emoji: '🪐',
    topics: ['physics/space/solar-system'],
    component: lazy(() => import('./physics/solar-system/SolarSystem')),
  },
  {
    id: 'goldilocks-lab',
    title: 'Goldilocks Planet Lab',
    description: 'Change a planet\'s distance, atmosphere and reflectiveness to keep its water liquid.',
    subject: 'physics',
    emoji: '🌡️',
    topics: ['physics/space/our-home-earth'],
    component: lazy(() => import('./physics/goldilocks-lab/GoldilocksLab')),
  },
  {
    id: 'moon-commander',
    title: 'Boss: Moon Commander',
    description: 'Control the Moon\'s position to create phases and eclipses on command.',
    subject: 'physics',
    emoji: '🌕',
    topics: ['physics/space/moon-commander'],
    component: lazy(() => import('./physics/moon-commander/MoonCommander')),
  },
  {
    id: 'alive-lab',
    title: 'Is It Alive?',
    description: 'Living or non-living? Test ten things against the seven life processes (MRS GREN).',
    subject: 'biology',
    emoji: '🌱',
    topics: ['biology/living-things/what-is-alive'],
    component: lazy(() => import('./biology/alive-lab/AliveLab')),
  },
  {
    id: 'germination-lab',
    title: 'Germination Lab',
    description: 'Set up four jars to find out what bean seeds need to germinate.',
    subject: 'biology',
    emoji: '🫘',
    topics: ['biology/living-things/seeds-and-germination'],
    component: lazy(() => import('./biology/germination-lab/GerminationLab')),
  },
  {
    id: 'plant-sorter',
    title: 'Plant Sorter',
    description: 'Sort plants by height, roots and leaf veins, and discover the monocot–dicot pattern.',
    subject: 'biology',
    emoji: '🌾',
    topics: ['biology/living-things/grouping-plants'],
    component: lazy(() => import('./biology/plant-sorter/PlantSorter')),
  },
  {
    id: 'adaptation-lab',
    title: 'Adapt-o-matic',
    description: 'Design an animal that survives the Thar Desert, the Himalaya, the sea or the rainforest.',
    subject: 'biology',
    emoji: '🐫',
    topics: ['biology/living-things/habitats-and-adaptations'],
    component: lazy(() => import('./biology/adaptation-lab/AdaptationLab')),
  },
  {
    id: 'key-builder',
    title: 'Key Builder',
    description: 'Build a dichotomous key with yes/no questions that identifies eight animals.',
    subject: 'biology',
    emoji: '🔑',
    topics: ['biology/living-things/dichotomous-keys'],
    component: lazy(() => import('./biology/key-builder/KeyBuilder')),
  },
  {
    id: 'kingdom-sorter',
    title: 'Kingdom Sorter',
    description: 'Sort organisms into the five kingdoms and the five classes of vertebrates.',
    subject: 'biology',
    emoji: '🐅',
    topics: ['biology/living-things/classifying-life'],
    component: lazy(() => import('./biology/kingdom-sorter/KingdomSorter')),
  },
  {
    id: 'ghats-guide',
    title: 'Boss: Western Ghats Field Guide',
    description: 'Identify eight organisms of the Western Ghats using a key.',
    subject: 'biology',
    emoji: '🔭',
    topics: ['biology/living-things/ghats-field-guide'],
    component: lazy(() => import('./biology/ghats-guide/GhatsGuide')),
  },
  {
    id: 'virtual-microscope',
    title: 'Virtual Microscope',
    description: 'Focus, stain and zoom from 40× to 1000× on onion peel, cheek cells, leaves, bacteria, blood and nerve cells.',
    subject: 'biology',
    emoji: '🔬',
    topics: ['biology/cells/microscopes-and-cells'],
    component: lazy(() => import('./biology/virtual-microscope/VirtualMicroscope')),
  },
  {
    id: 'cell-builder',
    title: 'Cell Builder',
    description: 'Build a plant cell and an animal cell, organelle by organelle.',
    subject: 'biology',
    emoji: '🧫',
    topics: ['biology/cells/plant-and-animal-cells'],
    component: lazy(() => import('./biology/cell-builder/CellBuilder')),
  },
  {
    id: 'cell-shapes',
    title: 'Cells for Every Job',
    description: 'Match specialised cells to their jobs, and find out why cells are so small.',
    subject: 'biology',
    emoji: '🧠',
    topics: ['biology/cells/specialised-cells'],
    component: lazy(() => import('./biology/cell-shapes/CellShapes')),
  },
  {
    id: 'organisation-zoom',
    title: 'Zoom Ladder',
    description: 'Zoom from a cell to a whole organism, and sort examples by level of organisation.',
    subject: 'biology',
    emoji: '🪜',
    topics: ['biology/cells/levels-of-organisation'],
    component: lazy(() => import('./biology/organisation-zoom/OrganisationZoom')),
  },
  {
    id: 'cell-division',
    title: 'One Cell to Many',
    description: 'Watch cells double, and see how fast bacteria multiply in food left out.',
    subject: 'biology',
    emoji: '🔁',
    topics: ['biology/cells/cell-division'],
    component: lazy(() => import('./biology/cell-division/CellDivision')),
  },
  {
    id: 'mystery-slides',
    title: 'Boss: Mystery Slides',
    description: 'Focus the microscope and identify six unlabelled slides.',
    subject: 'biology',
    emoji: '🧪',
    topics: ['biology/cells/mystery-slides'],
    component: lazy(() => import('./biology/mystery-slides/MysterySlides')),
  },
  {
    id: 'microbe-zoo',
    title: 'Microbe Zoo',
    description: 'Look at pond water, curd, soil and more under the microscope, and meet twelve microbes: friends and foes.',
    subject: 'biology',
    emoji: '🦠',
    topics: ['biology/microbes/meet-the-microbes'],
    component: lazy(() => import('./biology/microbe-zoo/MicrobeZoo')),
  },
  {
    id: 'fermentation-lab',
    title: 'Fermentation Lab',
    description: 'Make dough rise with yeast and set curd with Lactobacillus. Find the best temperature for each.',
    subject: 'biology',
    emoji: '🍞',
    topics: ['biology/microbes/fermentation'],
    component: lazy(() => import('./biology/fermentation-lab/FermentationLab')),
  },
  {
    id: 'compost-lab',
    title: 'Decomposers and Nitrogen Fixers',
    description: 'Run a kitchen compost bin, and see how Rhizobium in root nodules feeds the soil.',
    subject: 'biology',
    emoji: '♻️',
    topics: ['biology/microbes/decomposers-and-nitrogen'],
    component: lazy(() => import('./biology/compost-lab/CompostLab')),
  },
  {
    id: 'food-preserver',
    title: 'Food Preserver',
    description: 'Compare how fast microbes grow in food that is refrigerated, boiled, salted, sugared or dried.',
    subject: 'biology',
    emoji: '🧂',
    topics: ['biology/microbes/spoilage-and-preservation'],
    component: lazy(() => import('./biology/food-preserver/FoodPreserver')),
  },
  {
    id: 'petri-lab',
    title: 'Petri Dish Lab',
    description: 'Test antibiotics, soap and sanitiser on bacteria, meet a resistant strain, and see why handwashing works.',
    subject: 'biology',
    emoji: '🧫',
    topics: ['biology/microbes/antibiotics-and-hygiene'],
    component: lazy(() => import('./biology/petri-lab/PetriLab')),
  },
  {
    id: 'idli-chef',
    title: 'Boss: Idli Master Chef',
    description: 'Ferment idli batter, set curd and store leftovers safely in a South Indian kitchen.',
    subject: 'biology',
    emoji: '👩‍🍳',
    topics: ['biology/microbes/idli-master-chef'],
    component: lazy(() => import('./biology/idli-chef/IdliChef')),
  },
  {
    id: 'food-tests',
    title: 'Food Test Lab',
    description: 'Test ten foods for starch, protein and fat with iodine, copper sulphate and the paper test.',
    subject: 'biology',
    emoji: '🧪',
    topics: ['biology/nutrition/nutrients-and-food-tests'],
    component: lazy(() => import('./biology/food-tests/FoodTests')),
  },
  {
    id: 'thali-builder',
    title: 'Build a Balanced Thali',
    description: 'Plan a healthy Indian lunch with every food group in the right amount.',
    subject: 'biology',
    emoji: '🍛',
    topics: ['biology/nutrition/balanced-diet'],
    component: lazy(() => import('./biology/thali-builder/ThaliBuilder')),
  },
  {
    id: 'photosynthesis-factory',
    title: 'Photosynthesis Factory',
    description: 'Control light, CO₂, water and temperature for a water plant, find the limiting factor, and test a leaf for starch.',
    subject: 'biology',
    emoji: '🌿',
    topics: ['biology/nutrition/photosynthesis'],
    component: lazy(() => import('./biology/photosynthesis-factory/PhotosynthesisFactory')),
  },
  {
    id: 'nutrition-modes',
    title: 'Who Feeds How?',
    description: 'Autotrophs, parasites, insectivorous plants, saprotrophs and symbionts: sort ten organisms.',
    subject: 'biology',
    emoji: '🏺',
    topics: ['biology/nutrition/modes-of-nutrition'],
    component: lazy(() => import('./biology/nutrition-modes/NutritionModes')),
  },
  {
    id: 'digestion-journey',
    title: 'Digestion Journey',
    description: 'Follow a bite of food through the digestive system, and test how saliva digests starch.',
    subject: 'biology',
    emoji: '🍽️',
    topics: ['biology/nutrition/digestion'],
    component: lazy(() => import('./biology/digestion-journey/DigestionJourney')),
  },
  {
    id: 'diet-doctor',
    title: 'Boss: Diet Doctor',
    description: 'Diagnose six nutrient deficiencies from symptoms and prescribe the right foods.',
    subject: 'biology',
    emoji: '🩺',
    topics: ['biology/nutrition/diet-doctor'],
    component: lazy(() => import('./biology/diet-doctor/DietDoctor')),
  },
  {
    id: 'breathing-lab',
    title: 'Breathing Lab',
    description: 'A bell-jar lung model, breathing rates during exercise, and the limewater test on exhaled air.',
    subject: 'biology',
    emoji: '🫁',
    topics: ['biology/body/breathing-and-respiration'],
    component: lazy(() => import('./biology/breathing-lab/BreathingLab')),
  },
  {
    id: 'heart-pump',
    title: 'Heart Pump',
    description: 'Trace blood\'s double loop through the heart, see how heart rate changes blood flow, and find out what blood is made of.',
    subject: 'biology',
    emoji: '🫀',
    topics: ['biology/body/heart-and-circulation'],
    component: lazy(() => import('./biology/heart-pump/HeartPump')),
  },
  {
    id: 'kidney-filter',
    title: 'Kidney Filter',
    description: 'Predict what ends up in urine, and see how the kidneys balance water on a hot day.',
    subject: 'biology',
    emoji: '🫘',
    topics: ['biology/body/excretion'],
    component: lazy(() => import('./biology/kidney-filter/KidneyFilter')),
  },
  {
    id: 'joint-explorer',
    title: 'Joints and Muscles',
    description: 'Bend an arm with the biceps and triceps, and explore five kinds of joints.',
    subject: 'biology',
    emoji: '💪',
    topics: ['biology/body/skeleton-and-movement'],
    component: lazy(() => import('./biology/joint-explorer/JointExplorer')),
  },
  {
    id: 'marathon-medic',
    title: 'Boss: Marathon Medic',
    description: 'Follow a runner through a half marathon and explain how their body systems respond.',
    subject: 'biology',
    emoji: '🏅',
    topics: ['biology/body/marathon-medic'],
    component: lazy(() => import('./biology/marathon-medic/MarathonMedic')),
  },
  {
    id: 'disease-sorter',
    title: 'How Does It Spread?',
    description: 'Sort twelve diseases by how they spread, and learn how to prevent each.',
    subject: 'biology',
    emoji: '🦠',
    topics: ['biology/health/health-and-disease'],
    component: lazy(() => import('./biology/disease-sorter/DiseaseSorter')),
  },
  {
    id: 'germ-spread',
    title: 'Germ Spread Classroom',
    description: 'Watch flu spread through a class of 30, and test handwashing, masks, ventilation and staying home.',
    subject: 'biology',
    emoji: '🤒',
    topics: ['biology/health/preventing-spread'],
    component: lazy(() => import('./biology/germ-spread/GermSpread')),
  },
  {
    id: 'immune-memory',
    title: 'Immune Memory',
    description: 'Compare first and second immune responses, and see how vaccines give the body a safe first meeting.',
    subject: 'biology',
    emoji: '🛡️',
    topics: ['biology/health/immunity-and-vaccines'],
    component: lazy(() => import('./biology/immune-memory/ImmuneMemory')),
  },
  {
    id: 'outbreak-sim',
    title: 'Outbreak Simulator',
    description: 'Set the vaccination rate for flu, COVID-19, polio or measles and find the herd-immunity level.',
    subject: 'biology',
    emoji: '📈',
    topics: ['biology/health/herd-immunity'],
    component: lazy(() => import('./biology/outbreak-sim/OutbreakSim')),
  },
  {
    id: 'lifestyle-planner',
    title: 'Healthy Day Planner',
    description: 'Balance sleep, activity, screen time and diet to lower the risk of non-communicable diseases.',
    subject: 'biology',
    emoji: '🗓️',
    topics: ['biology/health/healthy-lifestyle'],
    component: lazy(() => import('./biology/lifestyle-planner/LifestylePlanner')),
  },
  {
    id: 'outbreak-detective',
    title: 'Boss: Outbreak Detective',
    description: 'Identify a disease, map cases to find the contaminated well, and stop a cholera outbreak.',
    subject: 'biology',
    emoji: '🗺️',
    topics: ['biology/health/outbreak-detective'],
    component: lazy(() => import('./biology/outbreak-detective/OutbreakDetective')),
  },
  {
    id: 'propagation-lab',
    title: 'New Plants Without Seeds',
    description: 'Grow potatoes, roses, Bryophyllum and more from parts of the parent plant, and explore other kinds of asexual reproduction.',
    subject: 'biology',
    emoji: '🥔',
    topics: ['biology/reproduction/asexual-reproduction'],
    component: lazy(() => import('./biology/propagation-lab/PropagationLab')),
  },
  {
    id: 'flower-lab',
    title: 'Flower Lab',
    description: 'Label the parts of a flower, then fly a bee between plants to see self- and cross-pollination.',
    subject: 'biology',
    emoji: '🌺',
    topics: ['biology/reproduction/flowers-and-pollination'],
    component: lazy(() => import('./biology/flower-lab/FlowerLab')),
  },
  {
    id: 'seed-dispersal',
    title: 'Seed Designer',
    description: 'Give seeds wings, hairs, hooks, husks or exploding pods, and see how far they travel.',
    subject: 'biology',
    emoji: '🪽',
    topics: ['biology/reproduction/seed-dispersal'],
    component: lazy(() => import('./biology/seed-dispersal/SeedDispersal')),
  },
  {
    id: 'life-cycles',
    title: 'Life Cycles',
    description: 'Put the stages of frog, silk moth, hen, cow and Hydra life cycles in order; sort animals that lay eggs from those that give birth.',
    subject: 'biology',
    emoji: '🐸',
    topics: ['biology/reproduction/reproduction-in-animals'],
    component: lazy(() => import('./biology/life-cycles/LifeCycles')),
  },
  {
    id: 'growing-up',
    title: 'Growing Up',
    description: 'Growth-spurt curves, the hormones of puberty, and myths vs facts about adolescence.',
    subject: 'biology',
    emoji: '🌱',
    topics: ['biology/reproduction/adolescence'],
    component: lazy(() => import('./biology/growing-up/GrowingUp')),
  },
  {
    id: 'master-gardener',
    title: 'Boss: Master Gardener',
    description: 'Solve six school-garden problems using propagation, pollination and seed dispersal.',
    subject: 'biology',
    emoji: '🌻',
    topics: ['biology/reproduction/master-gardener'],
    component: lazy(() => import('./biology/master-gardener/MasterGardener')),
  },
  {
    id: 'ecosystem-builder',
    title: 'Pond Ecosystem Builder',
    description: 'Sort a pond\'s living and non-living parts into producers, consumers, decomposers and abiotic factors.',
    subject: 'biology',
    emoji: '🪷',
    topics: ['biology/ecosystems/what-is-an-ecosystem'],
    component: lazy(() => import('./biology/ecosystem-builder/EcosystemBuilder')),
  },
  {
    id: 'food-web',
    title: 'Western Ghats Food Web',
    description: 'Remove a species and see who loses their food, then build your own food chains.',
    subject: 'biology',
    emoji: '🕸️',
    topics: ['biology/ecosystems/food-chains-and-webs'],
    component: lazy(() => import('./biology/food-web/FoodWeb')),
  },
  {
    id: 'energy-pyramid',
    title: 'Energy Pyramid',
    description: 'See how only about 10% of energy passes up each level of a food chain.',
    subject: 'biology',
    emoji: '🔺',
    topics: ['biology/ecosystems/energy-flow'],
    component: lazy(() => import('./biology/energy-pyramid/EnergyPyramid')),
  },
  {
    id: 'predator-prey',
    title: 'Predator and Prey',
    description: 'Watch grass, deer and tigers over 30 years, with and without poaching.',
    subject: 'biology',
    emoji: '🐅',
    topics: ['biology/ecosystems/balance-in-nature'],
    component: lazy(() => import('./biology/predator-prey/PredatorPrey')),
  },
  {
    id: 'conservation-planner',
    title: 'Conservation Planner',
    description: 'Plan a district with forests, corridors, farms, towns and mines that works for people and wildlife.',
    subject: 'biology',
    emoji: '🗺️',
    topics: ['biology/ecosystems/conservation'],
    component: lazy(() => import('./biology/conservation-planner/ConservationPlanner')),
  },
  {
    id: 'forest-keeper',
    title: 'Boss: Forest Keeper',
    description: 'Manage a tiger reserve for ten years and restore the balance of grass, deer and tigers.',
    subject: 'biology',
    emoji: '🌳',
    topics: ['biology/ecosystems/forest-keeper'],
    component: lazy(() => import('./biology/forest-keeper/ForestKeeper')),
  },
  {
    id: 'number-line-explorer',
    title: 'Number Line Explorer',
    description: 'Hop across zero to add and subtract integers, and solve real integer stories.',
    subject: 'mathematics',
    emoji: '🦘',
    topics: ['mathematics/number-systems/integers'],
    component: lazy(() => import('./mathematics/number-line-explorer/NumberLineExplorer')),
  },
  {
    id: 'sign-patterns',
    title: 'Sign Patterns',
    description: 'Discover why negative × negative is positive by continuing number patterns.',
    subject: 'mathematics',
    emoji: '🪜',
    topics: ['mathematics/number-systems/multiplying-integers'],
    component: lazy(() => import('./mathematics/sign-patterns/SignPatterns')),
  },
  {
    id: 'fraction-wall',
    title: 'Fraction Wall',
    description: 'Compare, find equivalent fractions and add them on a fraction wall.',
    subject: 'mathematics',
    emoji: '🧱',
    topics: ['mathematics/number-systems/fractions'],
    component: lazy(() => import('./mathematics/fraction-wall/FractionWall')),
  },
  {
    id: 'fraction-area-model',
    title: 'Fraction Area Model',
    description: 'See fraction multiplication as overlapping areas, and division as “how many fit?”',
    subject: 'mathematics',
    emoji: '🟩',
    topics: ['mathematics/number-systems/multiplying-dividing-fractions'],
    component: lazy(() => import('./mathematics/fraction-area-model/FractionAreaModel')),
  },
  {
    id: 'rational-zoom',
    title: 'Rational Zoom',
    description: 'Find which fractions give terminating or recurring decimals, and zoom in between rationals.',
    subject: 'mathematics',
    emoji: '🔭',
    topics: ['mathematics/number-systems/decimals-and-rationals'],
    component: lazy(() => import('./mathematics/rational-zoom/RationalZoom')),
  },
  {
    id: 'number-ninja',
    title: 'Boss: Number Ninja',
    description: 'Ten tricky problems with integers, fractions, decimals and rationals. Three lives.',
    subject: 'mathematics',
    emoji: '🥷',
    topics: ['mathematics/number-systems/number-ninja'],
    component: lazy(() => import('./mathematics/number-ninja/NumberNinja')),
  },
  {
    id: 'factor-tree',
    title: 'Factor Tree',
    description: 'Split numbers into primes with a factor tree, and find HCF and LCM from shared primes.',
    subject: 'mathematics',
    emoji: '🌳',
    topics: ['mathematics/squares-and-roots/primes-and-factors'],
    component: lazy(() => import('./mathematics/factor-tree/FactorTree')),
  },
  {
    id: 'square-builder',
    title: 'Square Builder',
    description: 'Build squares from odd L-shaped layers and learn which last digits squares can have.',
    subject: 'mathematics',
    emoji: '🟧',
    topics: ['mathematics/squares-and-roots/square-numbers'],
    component: lazy(() => import('./mathematics/square-builder/SquareBuilder')),
  },
  {
    id: 'locker-puzzle',
    title: 'The Locker Puzzle',
    description: '100 lockers, 100 people toggling them. Which stay open, and why?',
    subject: 'mathematics',
    emoji: '🚪',
    topics: ['mathematics/squares-and-roots/square-numbers'],
    component: lazy(() => import('./mathematics/locker-puzzle/LockerPuzzle')),
  },
  {
    id: 'root-finder',
    title: 'Root Finder',
    description: 'Squeeze a square root between perfect squares, pair up primes, and refine a guess.',
    subject: 'mathematics',
    emoji: '🎯',
    topics: ['mathematics/squares-and-roots/square-roots'],
    component: lazy(() => import('./mathematics/root-finder/RootFinder')),
  },
  {
    id: 'cube-builder',
    title: 'Cube Builder',
    description: 'Stack unit cubes, find cube roots by prime triples, and discover Ramanujan’s 1729.',
    subject: 'mathematics',
    emoji: '🧊',
    topics: ['mathematics/squares-and-roots/cubes-and-cube-roots'],
    component: lazy(() => import('./mathematics/cube-builder/CubeBuilder')),
  },
  {
    id: 'number-play',
    title: 'Number Play',
    description: 'Divisibility shortcuts, and the mystery of numbers that aren’t sums of consecutive numbers.',
    subject: 'mathematics',
    emoji: '🔍',
    topics: ['mathematics/squares-and-roots/number-play'],
    component: lazy(() => import('./mathematics/number-play/NumberPlay')),
  },
  {
    id: 'root-raider',
    title: 'Boss: Root Raider',
    description: 'Ten problems on squares, cubes, roots and number patterns. Three lives.',
    subject: 'mathematics',
    emoji: '🏴‍☠️',
    topics: ['mathematics/squares-and-roots/root-raider'],
    component: lazy(() => import('./mathematics/root-raider/RootRaider')),
  },
  {
    id: 'paper-fold',
    title: 'Paper Fold to the Moon',
    description: 'Fold a sheet of paper again and again. How many doublings reach Everest, the Moon, the Sun?',
    subject: 'mathematics',
    emoji: '📄',
    topics: ['mathematics/powers/exponents'],
    component: lazy(() => import('./mathematics/paper-fold/PaperFold')),
  },
  {
    id: 'exponent-laws',
    title: 'Exponent Laws',
    description: 'Write powers out as chips and watch the laws of exponents appear.',
    subject: 'mathematics',
    emoji: '✖️',
    topics: ['mathematics/powers/laws-of-exponents'],
    component: lazy(() => import('./mathematics/exponent-laws/ExponentLaws')),
  },
  {
    id: 'power-ladder',
    title: 'Power Ladder',
    description: 'Step down the powers of 2, 3, 5 and 10 to discover zero and negative exponents.',
    subject: 'mathematics',
    emoji: '🪜',
    topics: ['mathematics/powers/zero-and-negative-exponents'],
    component: lazy(() => import('./mathematics/power-ladder/PowerLadder')),
  },
  {
    id: 'scale-of-universe',
    title: 'Scale of the Universe',
    description: 'From atoms to galaxies in standard form, plus a standard-form writing challenge.',
    subject: 'mathematics',
    emoji: '🔭',
    topics: ['mathematics/powers/standard-form'],
    component: lazy(() => import('./mathematics/scale-of-universe/ScaleOfUniverse')),
  },
  {
    id: 'number-bases',
    title: 'Number Systems Explorer',
    description: 'See any number in binary, base 5, base 20, base 60 and Roman numerals.',
    subject: 'mathematics',
    emoji: '🏛️',
    topics: ['mathematics/powers/story-of-numbers'],
    component: lazy(() => import('./mathematics/number-bases/NumberBases')),
  },
  {
    id: 'power-surge',
    title: 'Boss: Power Surge',
    description: 'Ten problems on exponents, standard form and number systems. Three lives.',
    subject: 'mathematics',
    emoji: '⚡',
    topics: ['mathematics/powers/power-surge'],
    component: lazy(() => import('./mathematics/power-surge/PowerSurge')),
  },
  {
    id: 'matchstick-patterns',
    title: 'Matchstick Patterns',
    description: 'Grow matchstick patterns and find the rule a × n + b that predicts any size.',
    subject: 'mathematics',
    emoji: '🔥',
    topics: ['mathematics/algebra/letter-numbers'],
    component: lazy(() => import('./mathematics/matchstick-patterns/MatchstickPatterns')),
  },
  {
    id: 'algebra-tiles',
    title: 'Algebra Tiles',
    description: 'Build expressions with x², x and unit tiles; cancel zero pairs and collect like terms.',
    subject: 'mathematics',
    emoji: '🧩',
    topics: ['mathematics/algebra/simplifying-expressions'],
    component: lazy(() => import('./mathematics/algebra-tiles/AlgebraTiles')),
  },
  {
    id: 'area-multiplier',
    title: 'Area Multiplier',
    description: 'Multiply numbers and expressions by splitting a rectangle into parts.',
    subject: 'mathematics',
    emoji: '🟦',
    topics: ['mathematics/algebra/distributive-property'],
    component: lazy(() => import('./mathematics/area-multiplier/AreaMultiplier')),
  },
  {
    id: 'identity-visualiser',
    title: 'Identity Visualiser',
    description: 'See (a + b)² and a² − b² as shapes, then use them for mental maths.',
    subject: 'mathematics',
    emoji: '🟨',
    topics: ['mathematics/algebra/algebraic-identities'],
    component: lazy(() => import('./mathematics/identity-visualiser/IdentityVisualiser')),
  },
  {
    id: 'factor-rectangle',
    title: 'Factor Rectangle',
    description: 'Find the two numbers that turn x² + bx + c into a rectangle (x + m)(x + n).',
    subject: 'mathematics',
    emoji: '🧱',
    topics: ['mathematics/algebra/factorisation'],
    component: lazy(() => import('./mathematics/factor-rectangle/FactorRectangle')),
  },
  {
    id: 'number-trick',
    title: 'Algebra Magic Tricks',
    description: 'Think-of-a-number tricks, and the algebra that explains them.',
    subject: 'mathematics',
    emoji: '🎩',
    topics: ['mathematics/algebra/algebra-play'],
    component: lazy(() => import('./mathematics/number-trick/NumberTrick')),
  },
  {
    id: 'algebra-quest',
    title: 'Boss: Algebra Quest',
    description: 'Ten problems on expressions, expanding, identities and factorising. Three lives.',
    subject: 'mathematics',
    emoji: '🏆',
    topics: ['mathematics/algebra/algebra-quest'],
    component: lazy(() => import('./mathematics/algebra-quest/AlgebraQuest')),
  },
  {
    id: 'balance-scale',
    title: 'Balance Scale',
    description: 'Solve equations on a pan balance: do the same to both sides.',
    subject: 'mathematics',
    emoji: '⚖️',
    topics: ['mathematics/equations/equations-and-balance'],
    component: lazy(() => import('./mathematics/balance-scale/BalanceScale')),
  },
  {
    id: 'step-solver',
    title: 'Step Solver',
    description: 'Solve linear equations one balanced step at a time, with brackets and fractions.',
    subject: 'mathematics',
    emoji: '🪜',
    topics: ['mathematics/equations/solving-linear-equations'],
    component: lazy(() => import('./mathematics/step-solver/StepSolver')),
  },
  {
    id: 'word-problems',
    title: 'Story to Equation',
    description: 'Turn stories about ages, coins and fares into equations and solve them.',
    subject: 'mathematics',
    emoji: '📖',
    topics: ['mathematics/equations/word-problems'],
    component: lazy(() => import('./mathematics/word-problems/WordProblems')),
  },
  {
    id: 'plot-it',
    title: 'Plot It',
    description: 'Plot points on a coordinate grid and complete shapes.',
    subject: 'mathematics',
    emoji: '📍',
    topics: ['mathematics/equations/coordinates'],
    component: lazy(() => import('./mathematics/plot-it/PlotIt')),
  },
  {
    id: 'line-grapher',
    title: 'Line Grapher',
    description: 'Explore y = mx + c with real situations like fares and temperatures.',
    subject: 'mathematics',
    emoji: '📈',
    topics: ['mathematics/equations/linear-graphs'],
    component: lazy(() => import('./mathematics/line-grapher/LineGrapher')),
  },
  {
    id: 'graph-stories',
    title: 'Graph Stories',
    description: 'Match real-life graphs to the stories they tell.',
    subject: 'mathematics',
    emoji: '📊',
    topics: ['mathematics/equations/graph-stories'],
    component: lazy(() => import('./mathematics/graph-stories/GraphStories')),
  },
  {
    id: 'equation-escape',
    title: 'Boss: Equation Escape',
    description: 'Open ten locks with equations, coordinates and graphs. Three lives.',
    subject: 'mathematics',
    emoji: '🗝️',
    topics: ['mathematics/equations/equation-escape'],
    component: lazy(() => import('./mathematics/equation-escape/EquationEscape')),
  },
  {
    id: 'ratio-mixer',
    title: 'Ratio Mixer',
    description: 'Mix paint in a ratio, share money fairly with a bar model, and read map scales.',
    subject: 'mathematics',
    emoji: '🎨',
    topics: ['mathematics/proportion/ratios'],
    component: lazy(() => import('./mathematics/ratio-mixer/RatioMixer')),
  },
  {
    id: 'recipe-scaler',
    title: 'Recipe Scaler',
    description: 'Scale a masala chai recipe with the unitary method, and convert units.',
    subject: 'mathematics',
    emoji: '☕',
    topics: ['mathematics/proportion/direct-proportion'],
    component: lazy(() => import('./mathematics/recipe-scaler/RecipeScaler')),
  },
  {
    id: 'workers-and-days',
    title: 'Workers and Days',
    description: 'More workers, fewer days: explore inverse proportion.',
    subject: 'mathematics',
    emoji: '👷',
    topics: ['mathematics/proportion/inverse-proportion'],
    component: lazy(() => import('./mathematics/workers-and-days/WorkersAndDays')),
  },
  {
    id: 'percent-bar',
    title: 'Percent Grid',
    description: 'Percentages on a hundred grid, and percentage increase and decrease.',
    subject: 'mathematics',
    emoji: '💯',
    topics: ['mathematics/proportion/percentages'],
    component: lazy(() => import('./mathematics/percent-bar/PercentBar')),
  },
  {
    id: 'market-stall',
    title: 'Market Stall',
    description: 'Run a stall: cost price, marked price, discount, profit and GST.',
    subject: 'mathematics',
    emoji: '🏪',
    topics: ['mathematics/proportion/profit-loss-discount'],
    component: lazy(() => import('./mathematics/market-stall/MarketStall')),
  },
  {
    id: 'interest-growth',
    title: 'Interest and Growth',
    description: 'Compare simple and compound interest, and watch a scooter depreciate.',
    subject: 'mathematics',
    emoji: '🏦',
    topics: ['mathematics/proportion/interest-and-growth'],
    component: lazy(() => import('./mathematics/interest-growth/InterestGrowth')),
  },
  {
    id: 'market-master',
    title: 'Boss: Market Master',
    description: 'Ten real-life problems on ratio, proportion, percentages and interest. Three lives.',
    subject: 'mathematics',
    emoji: '🏆',
    topics: ['mathematics/proportion/market-master'],
    component: lazy(() => import('./mathematics/market-master/MarketMaster')),
  },
  {
    id: 'angle-explorer',
    title: 'Angle Explorer',
    description: 'A transversal across parallel lines: corresponding, alternate and co-interior angles.',
    subject: 'mathematics',
    emoji: '📐',
    topics: ['mathematics/geometry/angles-and-parallel-lines'],
    component: lazy(() => import('./mathematics/angle-explorer/AngleExplorer')),
  },
  {
    id: 'triangle-lab',
    title: 'Triangle Lab',
    description: 'Drag a triangle’s corners to see the angle sum and exterior angle; test the triangle inequality.',
    subject: 'mathematics',
    emoji: '🔺',
    topics: ['mathematics/geometry/triangles'],
    component: lazy(() => import('./mathematics/triangle-lab/TriangleLab')),
  },
  {
    id: 'congruence-checker',
    title: 'Geometric Twins',
    description: 'Which facts guarantee two triangles are congruent? SSS, SAS, ASA, RHS, and two that fail.',
    subject: 'mathematics',
    emoji: '👯',
    topics: ['mathematics/geometry/congruence'],
    component: lazy(() => import('./mathematics/congruence-checker/CongruenceChecker')),
  },
  {
    id: 'quad-family',
    title: 'Quadrilateral Family',
    description: 'Properties of squares, rectangles, rhombuses, parallelograms, trapeziums and kites; polygon angle sums.',
    subject: 'mathematics',
    emoji: '🔷',
    topics: ['mathematics/geometry/quadrilaterals'],
    component: lazy(() => import('./mathematics/quad-family/QuadFamily')),
  },
  {
    id: 'pythagoras-lab',
    title: 'Baudhayana–Pythagoras Lab',
    description: 'Squares on the sides of a right triangle, testing for right angles, and ladder problems.',
    subject: 'mathematics',
    emoji: '📏',
    topics: ['mathematics/geometry/pythagoras'],
    component: lazy(() => import('./mathematics/pythagoras-lab/PythagorasLab')),
  },
  {
    id: 'tiling-studio',
    title: 'Tiling Studio',
    description: 'Which regular polygons fit around a point? Tile with one shape or mix them.',
    subject: 'mathematics',
    emoji: '🐝',
    topics: ['mathematics/geometry/tilings-and-symmetry'],
    component: lazy(() => import('./mathematics/tiling-studio/TilingStudio')),
  },
  {
    id: 'geometry-guardian',
    title: 'Boss: Geometry Guardian',
    description: 'Ten problems on angles, triangles, quadrilaterals, Pythagoras and tiling. Three lives.',
    subject: 'mathematics',
    emoji: '🛡️',
    topics: ['mathematics/geometry/geometry-guardian'],
    component: lazy(() => import('./mathematics/geometry-guardian/GeometryGuardian')),
  },
  {
    id: 'shear-it',
    title: 'Cut and Rearrange',
    description: 'Turn parallelograms, triangles and trapeziums into rectangles to see their area formulas.',
    subject: 'mathematics',
    emoji: '✂️',
    topics: ['mathematics/mensuration/area-of-shapes'],
    component: lazy(() => import('./mathematics/shear-it/ShearIt')),
  },
  {
    id: 'geoboard',
    title: 'Geoboard',
    description: 'Make polygons on a pegboard and find their areas, then check with Pick’s theorem.',
    subject: 'mathematics',
    emoji: '📌',
    topics: ['mathematics/mensuration/polygon-area'],
    component: lazy(() => import('./mathematics/geoboard/Geoboard')),
  },
  {
    id: 'circle-lab',
    title: 'Circle Lab',
    description: 'Unroll a circle to meet π, and slice it into sectors to find its area.',
    subject: 'mathematics',
    emoji: '⭕',
    topics: ['mathematics/mensuration/circles'],
    component: lazy(() => import('./mathematics/circle-lab/CircleLab')),
  },
  {
    id: 'cube-nets',
    title: 'Nets and Solids',
    description: 'Find all 11 nets of a cube, and discover Euler’s formula F + V − E = 2.',
    subject: 'mathematics',
    emoji: '🧊',
    topics: ['mathematics/mensuration/nets-and-solids'],
    component: lazy(() => import('./mathematics/cube-nets/CubeNets')),
  },
  {
    id: 'surface-area',
    title: 'Surface Area Unfolded',
    description: 'Unfold cuboids and cylinders into nets and add up the faces.',
    subject: 'mathematics',
    emoji: '📦',
    topics: ['mathematics/mensuration/surface-area'],
    component: lazy(() => import('./mathematics/surface-area/SurfaceArea')),
  },
  {
    id: 'volume-builder',
    title: 'Volume Builder',
    description: 'Build boxes from unit cubes, stack cylinder layers, and fill a water tank.',
    subject: 'mathematics',
    emoji: '💧',
    topics: ['mathematics/mensuration/volume'],
    component: lazy(() => import('./mathematics/volume-builder/VolumeBuilder')),
  },
  {
    id: 'space-architect',
    title: 'Boss: Space Architect',
    description: 'Ten problems on area, circles, nets, surface area and volume. Three lives.',
    subject: 'mathematics',
    emoji: '🏗️',
    topics: ['mathematics/mensuration/space-architect'],
    component: lazy(() => import('./mathematics/space-architect/SpaceArchitect')),
  },
  {
    id: 'frequency-builder',
    title: 'Frequency Builder',
    description: 'Group 40 heights into class intervals with tally marks and a histogram.',
    subject: 'mathematics',
    emoji: '📋',
    topics: ['mathematics/data/collecting-data'],
    component: lazy(() => import('./mathematics/frequency-builder/FrequencyBuilder')),
  },
  {
    id: 'dot-plot-balance',
    title: 'Dot Plot Balance',
    description: 'Build a dot plot and see the mean as a balance point, the median, mode and range.',
    subject: 'mathematics',
    emoji: '⚖️',
    topics: ['mathematics/data/averages'],
    component: lazy(() => import('./mathematics/dot-plot-balance/DotPlotBalance')),
  },
  {
    id: 'chart-maker',
    title: 'Chart Maker',
    description: 'Show data as bar, pie and line charts, and spot how a cut axis misleads.',
    subject: 'mathematics',
    emoji: '📊',
    topics: ['mathematics/data/charts-and-graphs'],
    component: lazy(() => import('./mathematics/chart-maker/ChartMaker')),
  },
  {
    id: 'dice-lab',
    title: 'Dice Lab',
    description: 'Roll dice thousands of times and compare experiment with theory.',
    subject: 'mathematics',
    emoji: '🎲',
    topics: ['mathematics/data/chance-and-experiments'],
    component: lazy(() => import('./mathematics/dice-lab/DiceLab')),
  },
  {
    id: 'sample-space',
    title: 'Sample Space',
    description: 'All 36 outcomes of two dice: count favourable outcomes to find probabilities.',
    subject: 'mathematics',
    emoji: '🔢',
    topics: ['mathematics/data/probability'],
    component: lazy(() => import('./mathematics/sample-space/SampleSpace')),
  },
  {
    id: 'data-detective',
    title: 'Boss: Data Detective',
    description: 'Ten cases on averages, charts and chance. Three lives.',
    subject: 'mathematics',
    emoji: '🕵️',
    topics: ['mathematics/data/data-detective'],
    component: lazy(() => import('./mathematics/data-detective/DataDetective')),
  },
  {
    id: 'displacement-walker',
    title: 'Distance vs Displacement',
    description: 'Walk the streets to school and compare distance, displacement, speed and velocity.',
    subject: 'physics',
    emoji: '🧭',
    topics: ['physics/kinematics/distance-and-displacement'],
    component: lazy(() => import('./physics/displacement-walker/DisplacementWalker')),
  },
  {
    id: 'acceleration-track',
    title: 'Acceleration Track',
    description: 'A ticker-tape track: see velocity change at a steady rate, speeding up or braking.',
    subject: 'physics',
    emoji: '🚗',
    topics: ['physics/kinematics/acceleration'],
    component: lazy(() => import('./physics/acceleration-track/AccelerationTrack')),
  },
  {
    id: 'motion-grapher',
    title: 'Motion Grapher',
    description: 'Build journeys and read their velocity–time and displacement–time graphs.',
    subject: 'physics',
    emoji: '📈',
    topics: ['physics/kinematics/motion-graphs'],
    component: lazy(() => import('./physics/motion-grapher/MotionGrapher')),
  },
  {
    id: 'suvat-solver',
    title: 'Equations of Motion',
    description: 'Solve metro, coconut and cricket-ball problems with v = u + at and friends.',
    subject: 'physics',
    emoji: '🧮',
    topics: ['physics/kinematics/equations-of-motion'],
    component: lazy(() => import('./physics/suvat-solver/SuvatSolver')),
  },
  {
    id: 'circular-motion',
    title: 'Circular Motion',
    description: 'Whirl a stone on a string, watch its velocity turn, then let go.',
    subject: 'physics',
    emoji: '🎡',
    topics: ['physics/kinematics/circular-motion'],
    component: lazy(() => import('./physics/circular-motion/CircularMotion')),
  },
  {
    id: 'motion-master',
    title: 'Boss: Motion Master',
    description: 'Ten problems on displacement, velocity, acceleration and motion graphs. Three lives.',
    subject: 'physics',
    emoji: '🏎️',
    topics: ['physics/kinematics/motion-master'],
    component: lazy(() => import('./physics/motion-master/MotionMaster')),
  },
  {
    id: 'force-arena',
    title: 'Force Arena',
    description: 'Push a crate with two teams on different floors: balanced and unbalanced forces, friction and inertia.',
    subject: 'physics',
    emoji: '⚖️',
    topics: ['physics/forces-and-laws/balanced-forces'],
    component: lazy(() => import('./physics/force-arena/ForceArena')),
  },
  {
    id: 'newtons-second-law',
    title: "Newton's Second Law",
    description: 'Time a trolley between light gates, change force and mass, and discover F = ma.',
    subject: 'physics',
    emoji: '🛒',
    topics: ['physics/forces-and-laws/second-law'],
    component: lazy(() => import('./physics/newtons-second-law/SecondLaw')),
  },
  {
    id: 'action-reaction',
    title: 'Action and Reaction',
    description: 'Two skaters push apart on ice: equal and opposite forces, different accelerations.',
    subject: 'physics',
    emoji: '⛸️',
    topics: ['physics/forces-and-laws/third-law'],
    component: lazy(() => import('./physics/action-reaction/ActionReaction')),
  },
  {
    id: 'collision-lab',
    title: 'Collision Lab',
    description: 'Crash carts together, bouncy or sticky, and check that momentum is conserved.',
    subject: 'physics',
    emoji: '💥',
    topics: ['physics/forces-and-laws/momentum'],
    component: lazy(() => import('./physics/collision-lab/CollisionLab')),
  },
  {
    id: 'weight-on-worlds',
    title: 'Weight on Other Worlds',
    description: 'Mass stays the same, weight changes: from the Moon to Jupiter, and up to orbit.',
    subject: 'physics',
    emoji: '🌙',
    topics: ['physics/forces-and-laws/gravitation'],
    component: lazy(() => import('./physics/weight-on-worlds/WeightOnWorlds')),
  },
  {
    id: 'force-master',
    title: 'Boss: Force Master',
    description: 'Ten problems on forces, Newton’s laws, momentum and weight. Three lives!',
    subject: 'physics',
    emoji: '🏋️',
    topics: ['physics/forces-and-laws/force-master'],
    component: lazy(() => import('./physics/force-master/ForceMaster')),
  },
]

export const getLab = (id: string) => LABS.find((l) => l.id === id)
